name: resdev36
dependencies:
    - python=3
    - coverage
    - pyyaml
    - pandas==1.1.5
    - numpy
    - requests
    - sphinx
    - pip
    - pip:
          - arrow
          - cookiecutter
          - detect-secrets
          - myst-parser
          - more-itertools==5.0.0
          - numpy
          - pandas==1.1.5
          - postcodes_uk
          - pre-commit==2.17.0
          - pydoop
          - pytest #default version 5 which is compatible with postcodes_uk
          - pytest-cov
          - python-dotenv
          - readme-coverage-badger
          - setuptools
          - table_logger
          - toml
          - xlrd
