name: resdev36
dependencies:
- python=3.6.2
- pytest=3.2.1=py36_0
- pyyaml
- pandas=1.1.5
- numpy=1.19.5
- requests
- sphinx
- pip
- pip:
  - arrow
  - cookiecutter
  - detect-secrets
  - myst-parser
  - pre-commit==2.17.0
  - python-dotenv
