name: resdev36
dependencies:
- python=3
- coverage
- pyyaml
- requests
- sphinx
- pip
- pip:
  - arrow
  - cookiecutter
  - detect-secrets
  - myst-parser
  - pre-commit==2.17.0
  - python-dotenv
  - table_logger
  - pandas==1.1.5
  - numpy
  - pydoop
  - setuptools
  - pytest
