name: resdev36
dependencies:
    - python=3
    - coverage
    - pytest
    - pytest-cov
    - pyyaml
    - pandas
    - numpy
    - requests
    - sphinx
    - pip
    - pip:
          - arrow
          - cookiecutter
          - detect-secrets
          - myst-parser
          - pre-commit==2.17.0
          - pydoop
          - python-dotenv
          - table_logger
          - toml
          - xlrd
