[cell_id]
description = "Cell ID"
data_type = "Categorical"
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[civ_or_def]
description = "Business type: Civil or Defence"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[current_sic]
description = "Sic - Standard Industry Classification"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[data_source]
description = "Constructed"
data_type = "Categorical"
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[emp_other]
description = "emp_other (Full Time Equivalent)"
data_type = "Numeric float (or decimal)"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[emp_researcher]
description = "emp_researcher (Full Time Equivalent)"
data_type = "Numeric float (or decimal)"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[emp_technician]
description = "emp_technician (Full Time Equivalent)"
data_type = "Numeric float (or decimal)"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[emp_total]
description = "emp_total (Full Time Equivalent)"
data_type = "Numeric float (or decimal)"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[employee_count]
description = "Employee Count (IDBR)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[foreign_owner]
description = "Foreign Owner"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[form_status]
description = "Status"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[form_type]
description = "Form Type"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[freeze_id]
description = "Freeze ID - bespoke to openroad"
data_type = "Categorical"
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[headcount_oth_f]
description = "Other Female (Headcount)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[headcount_oth_m]
description = "Other Male (Headcount)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[headcount_res_f]
description = "Researchers Females (Headcount)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[headcount_res_m]
description = "Researchers Male (Headcount)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[headcount_tec_f]
description = "Technicians Female (Headcount)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[headcount_tec_m]
description = "Technicians Male (Headcount)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[headcount_total]
description = "Total Headcount"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[period]
description = "Openroad Specific"
data_type = "Categorical"
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[period_contributor_id]
description = "Openroad Specific"
data_type = "Categorical"
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[period_year]
description = "Period"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[product_group]
description = "Published Product Group"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[ru_ref]
description = "Reference"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[sizeband]
description = "SizeBand"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[wowentref]
description = "Wowentref"
data_type = "Categorical"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q202]
description = "Salaries & Wages"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q203]
description = "Other current expenditure"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q204]
description = "Total Current Expenditure"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q205]
description = "Basic Research"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q206]
description = "Applied Research"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q207]
description = "Experimental Development"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q208]
description = "Land & Build CapEx                "
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q209]
description = "Equipment & Machinery CapEx"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q210]
description = "Total Capex."
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q211]
description = "Total Inhouse Expenditure                         "
data_type = "Numeric Integer"
nullable = "No"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q212]
description = "Own Funds"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q213]
description = "Funding - Commission of the EU"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q214]
description = "Funding - UK government"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q215]
description = "Funding - Organisations outside the Uk                       "
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q216]
description = "Funding - Other UK Private Bus/Public Orgs                 "
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q217]
description = "Funding - Any Other UK                                         "
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q218]
description = "Total Funding                                     "
data_type = "Numeric Integer"
nullable = "No"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q219]
description = "Land Acquired for R&D (Split of Land & Build CapEx)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q220]
description = "Buildings acquired/constructed for R&D (Split of Land & Build CapEx)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q221]
description = "Expenditure on computer software only (of which from Equipment & Machinery CapEx)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q222]
description = "Purchase of Materials (Split of Other current)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q223]
description = "Purchase of Services (Split of Other current)"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q224]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q225]
description = "Ownership - Own Business"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q226]
description = "Ownership - UK Government"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q227]
description = "Ownership - Other UK Priv Bus"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q228]
description = "Ownership - Other UK Orgs"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q229]
description = "Ownership - Bus Enterprises in Group Outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q230]
description = "Ownership - Other Bus Enterprises outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q231]
description = "Ownership - Other Governments outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q232]
description = "Ownership - Higher Education Establishments outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q233]
description = "Ownership - Non-profit Orgs outside the UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q234]
description = "Ownership - Commission of EU"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q235]
description = "Ownership - International Orgs"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q236]
description = "Ownership - Any other Orgs outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q237]
description = "Ownership - not owned freely available"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q238]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q239]
description = "Life Length - Basic Research"
data_type = "Numeric Integer"
nullable = "Not Asked"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q240]
description = "Life Length - Applied Research"
data_type = "Numeric Integer"
nullable = "Not Asked"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q241]
description = "Life Length - Experimental Res"
data_type = "Numeric Integer"
nullable = "Not Asked"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q242]
description = "Funding - Any other UK organisations"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q243]
description = "Funding - Business Enterprises in group outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q244]
description = "Funding - Other Business Enterprises outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q245]
description = "Funding - Other Governments outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q246]
description = "Funding - Higher Education Est Outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q247]
description = "Funding - Non-profit Orgs outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q248]
description = "Funding - International Orgs"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q249]
description = "Funding - Any other orgs outside UK"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q250]
description = "Funding - UK Higher Education Establishments"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q251]
description = "Tax credit claim submitted or intended for In-house expenditure (Y/N) LONG FORM"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q252]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q253]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q254]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q255]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q256]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q257]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q258]
description = nan
data_type = nan
nullable = nan
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q302]
description = "Purchased/funded R&D in the UK (Yes or No)"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q303]
description = "Purchased Outside UK (Govt Funded)                "
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q304]
description = "Purchased Outside UK (Other)                "
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q305]
description = "Total Purchased"
data_type = "Numeric Integer"
nullable = "Yes"
min_acceptable_value = 0
max_acceptable_value = 1000000

[q307]
description = "Tax credit claim submitted or intended for purchased work commissioned in UK (Y/N) LONG FORM"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q308]
description = "Tax credit claim submitted/intended for purchased work outside Ukorig. Funded by UK gov (Y/N) LONG FORM"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q309]
description = "Tax credit claim submitted or intended for all other purchased work outside the UK (Y/N) LONG FORM"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q713]
description = "Tax credit claim submitted or intended for In-house expenditure (Y/N) SHORT FORM"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"

[q714]
description = "Tax credit claim submitted or intended for purchased R&D (Y/N) SHORT FORM"
data_type = "Boolean (True or False, 0 or 1)"
nullable = "No"
min_acceptable_value = "nan"
max_acceptable_value = "nan"
