[snapshot_id]
Description = "nan"
Deduced_Data_Type = "nan"
Nullable = "nan"
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["nan"]

[reference]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = 11001603625
Max_values = 19891309165
Possible_Categorical_Values = ["nan"]

[period]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = 6
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = [202012]

[survey]
Description = "All values are 002"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["002"]

[formid]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "int"
Length = 2
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = [20, 21]

[status]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["Clear", "Clear - overridden", "Form saved", "Clear - overridden SE", "Form sent out", "Check needed", "Combined child (NIL2)", "Out of scope (NIL3)", "Ceased trading (NIL4)", "Dormant (NIL5)", "Part year return (NIL8)", "No UK activity (NIL9)"]

[statusencoded]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "int"
Length = 3
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = [100, 200, 201, 210, 211, 301, 302, 303, 304, 305, 308, 309]

[receiptdate]
Description = "Datetime format = %Y-%m-%d %H:%M:%S.%f+00"
Deduced_Data_Type = "Datetime"
Nullable = False
Current_Data_Type = ["None","str"]
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["nan"]

[lockedby]
Description = "All empty strings"
Deduced_Data_Type = "pandas.NA"
Nullable = True
Current_Data_Type = ["None","str"]
Length = 0
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["nan"]

[lockeddate]
Description = "All None type"
Deduced_Data_Type = "pandas.NA"
Nullable = True
Current_Data_Type = ["None","str"]
Length = 0
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["nan"]

[formtype]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["0001", "0006"]

[checkletter]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = 1
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["T", "H", "F", "J", "D", "A", "K", "C", "B", "L", "S"]

[frozensicoutdated]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1120
Max_values = 93059
Possible_Categorical_Values = ["nan"]

[rusicoutdated]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1120
Max_values = 93059
Possible_Categorical_Values = ["nan"]

[frozensic]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1300
Max_values = 96090
Possible_Categorical_Values = ["nan"]

[rusic]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1300
Max_values = 96090
Possible_Categorical_Values = ["nan"]

[frozenemployees]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 272527
Possible_Categorical_Values = ["nan"]

[employees]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 272528
Possible_Categorical_Values = ["nan"]

[frozenemployment]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1
Max_values = 272527
Possible_Categorical_Values = ["nan"]

[employment]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1
Max_values = 272528
Possible_Categorical_Values = ["nan"]

[frozenfteemployment]
Description = "nan"
Deduced_Data_Type = "float"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0.0
Max_values = 177699.0
Possible_Categorical_Values = ["nan"]

[fteemployment]
Description = "nan"
Deduced_Data_Type = "float"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0.0
Max_values = 177699.5
Possible_Categorical_Values = ["nan"]

[frozenturnover]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 55277352
Possible_Categorical_Values = ["nan"]

[turnover]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 55277352
Possible_Categorical_Values = ["nan"]

[enterprisereference]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = 1001603625
Max_values = 9891309165
Possible_categorical_Values = ["nan"]

[wowenterprisereference]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = 1001603625
Max_values = 9891309165
Possible_categorical_Values = ["nan"]

[cellnumber]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "int"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = [0]

[currency]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["S", "E"]

[vatreference]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["VATREF"]

[payereference]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["PAYEREF"]

[companyregistrationnumber]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["CRN"]

[numberlivelocalunits]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 6063
Possible_categorical_Values = ["nan"]

[numberlivevat]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 255
Possible_categorical_Values = ["nan"]

[numberlivepaye]
Description = "nan"
Deduced_Data_Type = "int"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 0
Max_values = 24
Possible_categorical_Values = ["nan"]

[legalstatus]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = 1
Max_values = 4
Possible_Categorical_Values = [1, 2, 3, 4]

[reportingunitmarker]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["L", "E"]

[region]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["WW", "BB", "FE", "GG", "JG", "HH", "ED", "KJ", "XX", "AA", "DC", "GF", "BA"]

[birthdate]
Description = "Datetime format = format=%d/%m/%Y"
Deduced_Data_Type = "Datetime"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[referencename]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[referencepostcode]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[tradingstyle]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[selectiontype]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["L"]

[inclusionexclusion]
Description = 'All values are " "'
Deduced_Data_Type = "pandas.NA"
Nullable = False
Current_Data_Type = "str"
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[createdby]
Description = "nan"
Deduced_Data_Type = "str"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["ingestion"]

[createddate]
Description = "Datetime format = %Y-%m-%d %H:%M:%S.%f+00"
Deduced_Data_Type = "Datetime"
Nullable = False
Current_Data_Type = "str"
Length = ">=1"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[lastupdatedby]
Description = "nan"
Deduced_Data_Type = "category"
Nullable = False
Current_Data_Type = ["None","str"]
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_Categorical_Values = ["data_migration", "Cheri", "Adela", "David"]

[lastupdateddate]
Description = "Datetime format = %Y-%m-%d %H:%M:%S.%f+00"
Deduced_Data_Type = "Datetime"
Nullable = False
Current_Data_Type = ["None","str"]
Length = "nan"
Min_values = "nan"
Max_values = "nan"
Possible_categorical_Values = ["nan"]

[cell_id]
Description = Cell ID
Deduced_Data_Type = Categorical
Nullable = nan
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[civ_or_def]
Description = Business type: Civil or Defence
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[current_sic]
Description = Sic - Standard Industry Classification
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[data_source]
Description = Constructed
Deduced_Data_Type = Categorical
Nullable = nan
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[emp_other]
Description = emp_other (Full Time Equivalent)
Deduced_Data_Type = Numeric float (or decimal)
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[emp_researcher]
Description = emp_researcher (Full Time Equivalent)
Deduced_Data_Type = Numeric float (or decimal)
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[emp_technician]
Description = emp_technician (Full Time Equivalent)
Deduced_Data_Type = Numeric float (or decimal)
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[emp_total]
Description = emp_total (Full Time Equivalent)
Deduced_Data_Type = Numeric float (or decimal)
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[employee_count]
Description = Employee Count (IDBR)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[foreign_owner]
Description = Foreign Owner
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[form_status]
Description = Status
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[form_type]
Description = Form Type
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[freeze_id]
Description = Freeze ID - bespoke to openroad
Deduced_Data_Type = Categorical
Nullable = nan
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_oth_f]
Description = Other Female (Headcount)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_oth_m]
Description = Other Male (Headcount)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_res_f]
Description = Researchers Females (Headcount)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_res_m]
Description = Researchers Male (Headcount)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_tec_f]
Description = Technicians Female (Headcount)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_tec_m]
Description = Technicians Male (Headcount)
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[headcount_total]
Description = Total Headcount
Deduced_Data_Type = Numeric Integer
Nullable = Yes
Length =  # an integer of the length, or N/A
Min_values =  0
Max_values = 1000000
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[period]
Description = Openroad Specific
Deduced_Data_Type = Categorical
Nullable = nan
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[period_contributor_id]
Description = Openroad Specific
Deduced_Data_Type = Categorical
Nullable = nan
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[period_year]
Description = Period
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[product_group]
Description = Published Product Group
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[ru_ref]
Description = Reference
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[sizeband]
Description = SizeBand
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =


[wowentref]
Description = Wowentref
Deduced_Data_Type = Categorical
Nullable = No
Length =  # an integer of the length, or N/A
Min_values =  None
Max_values = None
Possible_categorical_Values = []
    [q_code]
    civ =
    def =
