[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[reference]
old_name = "ru_ref"
Deduced_Data_Type = "Int64"

[referencename]
old_name = "company name"
Deduced_Data_Type = "object"

[employment]
old_name = "ru_emp"
Deduced_Data_Type = "Int64"

[turnover]
old_name = "ru_turnover"
Deduced_Data_Type = "Int64"

[wowenterprisereference]
old_name = "wowref"
Deduced_Data_Type = "object"

[foc]
old_name = "ult FOC"
Deduced_Data_Type = "object"
