[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[reference]
old_name = "ruref"
Deduced_Data_Type = "Int64"

[referencename]
old_name = "company name"
Deduced_Data_Type = "object"

[employment]
old_name = "ru emp"
Deduced_Data_Type = "Int64"

[turnover]
old_name = "ru turnover"
Deduced_Data_Type = "Int64"

[legalstatus]
old_name = "legal status"
Deduced_Data_Type = "Int64"

[region]
old_name = "ru region"
Deduced_Data_Type = "object"

[enterprisereference]
old_name = "entref"
Deduced_Data_Type = "Int64"

[ent_emp_find_out]
old_name = "ent emp"
Deduced_Data_Type = "Int64"

[ent_turnover_find_out]
old_name = "ent turnover"
Deduced_Data_Type = "Int64"

[ent_region_find_out]
old_name = "ent region"
Deduced_Data_Type = "object"

[wowenterprisereference]
old_name = "wowref"
Deduced_Data_Type = "object"

[foc]
old_name = "ult FOC"
Deduced_Data_Type = "object"

[rusic_check_this]
old_name = "sic07"
Deduced_Data_Type = "Int64"

