[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[reference]
old_name = "ruref"
Deduced_Data_Type = "Int64"

[company name]
old_name = "company name"
Deduced_Data_Type = "object"

[ru emp]
old_name = "ru emp"
Deduced_Data_Type = "Int64"

[ru turnover]
old_name = "ru turnover"
Deduced_Data_Type = "Int64"

[legal status]
old_name = "legal status"
Deduced_Data_Type = "Int64"

[ru region]
old_name = "ru region"
Deduced_Data_Type = "object"

[entref]
old_name = "entref"
Deduced_Data_Type = "Int64"

[ent emp]
old_name = "ent emp"
Deduced_Data_Type = "Int64"

[ent turnover]
old_name = "ent turnover"
Deduced_Data_Type = "Int64"

[ent region]
old_name = "ent region"
Deduced_Data_Type = "object"

[wowref]
old_name = "wowref"
Deduced_Data_Type = "object"

[ult FOC]
old_name = "ult FOC"
Deduced_Data_Type = "object"

[sic07]
old_name = "sic07"
Deduced_Data_Type = "Int64"

