[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[reference]
old_name = "ru_ref"
Deduced_Data_Type = "Int64"

[rusic]
old_name = "current_sic"
Deduced_Data_Type = "Int64"

[200]
old_name = "q200"
Deduced_Data_Type = "str"

[201]
old_name = "q201"
Deduced_Data_Type = "Int64"

[202]
old_name = "q202"
Deduced_Data_Type = "float64"

[203]
old_name = "q203"
Deduced_Data_Type = "float64"

[204]
old_name = "q204"
Deduced_Data_Type = "float64"

[205]
old_name = "q205"
Deduced_Data_Type = "float64"

[206]
old_name = "q206"
Deduced_Data_Type = "float64"

[207 ]
old_name = "q207 "
Deduced_Data_Type = "float64"

[209]
old_name = "q209"
Deduced_Data_Type = "float64"

[210]
old_name = "q210"
Deduced_Data_Type = "float64"

[211]
old_name = "q211"
Deduced_Data_Type = "float64"

[251]
old_name = "q251"
Deduced_Data_Type = "Int64"

[212]
old_name = "q212"
Deduced_Data_Type = "float64"

[214]
old_name = "q214"
Deduced_Data_Type = "float64"

[216]
old_name = "q216"
Deduced_Data_Type = "float64"

[218]
old_name = "q218"
Deduced_Data_Type = "float64"

[219]
old_name = "q219"
Deduced_Data_Type = "float64"

[220]
old_name = "q220"
Deduced_Data_Type = "float64"

[221]
old_name = "q221"
Deduced_Data_Type = "float64"

[300]
old_name = "q300"
Deduced_Data_Type = "str"

[301]
old_name = "q301"
Deduced_Data_Type = "Int64"

[302]
old_name = "q302"
Deduced_Data_Type = "float64"

[307]
old_name = "q307"
Deduced_Data_Type = "Int64"

[303]
old_name = "q303"
Deduced_Data_Type = "float64"

[308]
old_name = "q308"
Deduced_Data_Type = "Int64"

[304]
old_name = "q304"
Deduced_Data_Type = "float64"

[309]
old_name = "q309"
Deduced_Data_Type = "Int64"

[305]
old_name = "q305"
Deduced_Data_Type = "float64"

[405]
old_name = "q405"
Deduced_Data_Type = "float64"

[406]
old_name = "q406"
Deduced_Data_Type = "float64"

[407]
old_name = "q407"
Deduced_Data_Type = "float64"

[408]
old_name = "q408"
Deduced_Data_Type = "float64"

[409]
old_name = "q409"
Deduced_Data_Type = "float64"

[410]
old_name = "q410"
Deduced_Data_Type = "float64"

[411]
old_name = "q411"
Deduced_Data_Type = "float64"

[412]
old_name = "q412"
Deduced_Data_Type = "float64"

[501]
old_name = "q501"
Deduced_Data_Type = "float64"

[502]
old_name = "q502"
Deduced_Data_Type = "float64"

[503]
old_name = "q503"
Deduced_Data_Type = "float64"

[504]
old_name = "q504"
Deduced_Data_Type = "float64"

[505]
old_name = "q505"
Deduced_Data_Type = "float64"

[506]
old_name = "q506"
Deduced_Data_Type = "float64"

[507]
old_name = "q507"
Deduced_Data_Type = "float64"

[508]
old_name = "q508"
Deduced_Data_Type = "float64"

[222]
old_name = "q222"
Deduced_Data_Type = "float64"

[223]
old_name = "q223"
Deduced_Data_Type = "float64"

[225]
old_name = "q225"
Deduced_Data_Type = "float64"

[226]
old_name = "q226"
Deduced_Data_Type = "float64"

[227]
old_name = "q227"
Deduced_Data_Type = "float64"

[228]
old_name = "q228"
Deduced_Data_Type = "float64"

[229]
old_name = "q229"
Deduced_Data_Type = "float64"

[237]
old_name = "q237"
Deduced_Data_Type = "float64"

[242]
old_name = "q242"
Deduced_Data_Type = "float64"

[243]
old_name = "q243"
Deduced_Data_Type = "float64"

[244]
old_name = "q244"
Deduced_Data_Type = "float64"

[245]
old_name = "q245"
Deduced_Data_Type = "float64"

[246]
old_name = "q246"
Deduced_Data_Type = "float64"

[247]
old_name = "q247"
Deduced_Data_Type = "float64"

[248]
old_name = "q248"
Deduced_Data_Type = "float64"

[249]
old_name = "q249"
Deduced_Data_Type = "float64"

[250]
old_name = "q250"
Deduced_Data_Type = "float64"
