["SIC 2007_CODE"]
Deduced_Data_Type = "Int64"

["2016 > Form PG"]
Deduced_Data_Type = "Int64"



# SIC 2003                 int64
# SIC 2003_Description    object
# SIC 2007_CODE            int64
# SIC 2007_Description    object
# Table 23 SIC Group      object
# 2010 Pub PG             object
# 2016 > Pub PG           object
# 2009 Form PG             int64
# 2010 Form PG             int64
# 2016 > Form PG           int64
# Comments                object
