title = "TOML Example config"

[period]
start_period = "1990-10-10"
end_period = "2000-10-05"

[source_file]
location = "D:/"
fileName = "file.txt"

[output_location]
hive_db = "hive.db"
tableName = "name.table"

[outlier_correction]
location = "D:/"
filename = "outliers.txt"
bool = true
