[cell_id]
Description = "Cell ID"
Deduced_Data_Type = "Categorical"
Nullable = "nan"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[civ_or_def]
Description = "Business type: Civil or Defence"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "c_or_d"

[current_sic]
Description = "Sic - Standard Industry Classification"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "sic92"

[data_source]
Description = "Constructed"
Deduced_Data_Type = "Categorical"
Nullable = "nan"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[employee_count]
Description = "Employee Count (IDBR)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[foreign_owner]
Description = "Foreign Owner"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "f_owner"

[form_status]
Description = "Status"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[form_type]
Description = "Form Type"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "form"

[freeze_id]
Description = "Freeze ID - bespoke to openroad"
Deduced_Data_Type = "Categorical"
Nullable = "nan"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[period]
Description = "Openroad Specific"
Deduced_Data_Type = "Categorical"
Nullable = "nan"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "period"

[period_contributor_id]
Description = "Openroad Specific"
Deduced_Data_Type = "Categorical"
Nullable = "nan"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[period_year]
Description = "Period"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "None"

[product_group]
Description = "Published Product Group"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "selgrpno"

[reference]
Description = "Reference"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "ref"

[sizeband]
Description = "SizeBand"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "sizebd"

[wowentref]
Description = "Wowentref"
Deduced_Data_Type = "Categorical"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = ""
old_ref = "wow"

[202]
Description = "Salaries & Wages"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q202"
old_ref = "slries"

[203]
Description = "Other current expenditure"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q203"
old_ref = "curr_oth"

[204]
Description = "Total Current Expenditure"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q204"
old_ref = "curr_tot"

[205]
Description = "Basic Research"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q205"
old_ref = "res_bas"

[206]
Description = "Applied Research"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q206"
old_ref = "res_app"

[207]
Description = "Experimental Development"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q207"
old_ref = "experm"

[208]
Description = "Land & Build CapEx"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q208"
old_ref = "c_lnd_bl"

[209]
Description = "Equipment & Machinery CapEx"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q209"
old_ref = "cxplm"

[210]
Description = "Total Capex."
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q210"
old_ref = "None"

[211]
Description = "Total Inhouse Expenditure"
Deduced_Data_Type = "int64"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q211"
old_ref = "intram"

[212]
Description = "Own Funds"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q212"
old_ref = "own_f"

[213]
Description = "Funding - Commission of the EU"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q213"
old_ref = "ovss_ec"

[214]
Description = "Funding - UK government"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q214"
old_ref = "ex_uk_gv"

[215]
Description = "Funding - Organisations outside the UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q215"
old_ref = "ex_uk_b"

[216]
Description = "Funding - Other UK Private Bus/Public Orgs"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q216"
old_ref = "ex_uk"

[217]
Description = "Funding - Any Other UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q217"
old_ref = "None"

[218]
Description = "Total Funding"
Deduced_Data_Type = "int64"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q218"
old_ref = "f_tot"

[219]
Description = "Land Acquired for R&D (Split of Land & Build CapEx)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q219"
old_ref = "None"

[220]
Description = "Buildings acquired/constructed for R&D (Split of Land & Build CapEx)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q220"
old_ref = "None"

[221]
Description = "Expenditure on computer software only (of which from Equipment & Machinery CapEx)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q221"
old_ref = "None"

[222]
Description = "Purchase of Materials (Split of Other current)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q222"
old_ref = "None"

[223]
Description = "Purchase of Services (Split of Other current)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q223"
old_ref = "None"

[225]
Description = "Ownership - Own Business"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q225"
old_ref = "None"

[226]
Description = "Ownership - UK Government"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q226"
old_ref = "None"

[227]
Description = "Ownership - Other UK Priv Bus"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q227"
old_ref = "None"

[228]
Description = "Ownership - Other UK Orgs"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q228"
old_ref = "None"

[229]
Description = "Ownership - Bus Enterprises in Group Outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q229"
old_ref = "None"

[230]
Description = "Ownership - Other Bus Enterprises outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q230"
old_ref = "None"

[231]
Description = "Ownership - Other Governments outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q231"
old_ref = "None"

[232]
Description = "Ownership - Higher Education Establishments outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q232"
old_ref = "None"

[233]
Description = "Ownership - Non-profit Orgs outside the UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q233"
old_ref = "None"

[234]
Description = "Ownership - Commission of EU"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q234"
old_ref = "None"

[235]
Description = "Ownership - International Orgs"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q235"
old_ref = "None"

[236]
Description = "Ownership - Any other Orgs outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q236"
old_ref = "None"

[237]
Description = "Ownership - not owned freely available"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q237"
old_ref = "None"

[239]
Description = "Life Length - Basic Research"
Deduced_Data_Type = "int64"
Nullable = "Not Asked"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q239"
old_ref = "None"

[240]
Description = "Life Length - Applied Research"
Deduced_Data_Type = "int64"
Nullable = "Not Asked"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q240"
old_ref = "None"

[241]
Description = "Life Length - Experimental Res"
Deduced_Data_Type = "int64"
Nullable = "Not Asked"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q241"
old_ref = "None"

[242]
Description = "Funding - Any other UK organisations"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q242"
old_ref = "None"

[243]
Description = "Funding - Business Enterprises in group outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q243"
old_ref = "None"

[244]
Description = "Funding - Other Business Enterprises outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q244"
old_ref = "None"

[245]
Description = "Funding - Other Governments outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q245"
old_ref = "None"

[246]
Description = "Funding - Higher Education Est Outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q246"
old_ref = "None"

[247]
Description = "Funding - Non-profit Orgs outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q247"
old_ref = "None"

[248]
Description = "Funding - International Orgs"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q248"
old_ref = "None"

[249]
Description = "Funding - Any other orgs outside UK"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q249"
old_ref = "None"

[250]
Description = "Funding - UK Higher Education Establishments"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q250"
old_ref = "None"

[251]
Description = "Tax credit claim submitted or intended for In-house expenditure (Y/N) LONG FORM"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q251"
old_ref = "None"

[302]
Description = "Purchased/funded R&D in the UK (Yes or No)"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q302"
old_ref = "None"

[303]
Description = "Purchased Outside UK (Govt Funded)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q303"
old_ref = "None"

[304]
Description = "Purchased Outside UK (Other)"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q304"
old_ref = "None"

[305]
Description = "Total Purchased"
Deduced_Data_Type = "int64"
Nullable = "Yes"
Length = "# an integer of the length, or N/A"
Min_values = 0
Max_values = 1000000
Possible_categorical_Values = []
q_code = "q305"
old_ref = "None"

[307]
Description = "Tax credit claim submitted or intended for purchased work commissioned in UK (Y/N) LONG FORM"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q307"
old_ref = "None"

[308]
Description = "Tax credit claim submitted/intended for purchased work outside Ukorig. Funded by UK gov (Y/N) LONG FORM"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q308"
old_ref = "None"

[309]
Description = "Tax credit claim submitted or intended for all other purchased work outside the UK (Y/N) LONG FORM"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q309"
old_ref = "None"

[713]
Description = "Tax credit claim submitted or intended for In-house expenditure (Y/N) SHORT FORM"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q713"
old_ref = "None"

[714]
Description = "Tax credit claim submitted or intended for purchased R&D (Y/N) SHORT FORM"
Deduced_Data_Type = "bool"
Nullable = "No"
Length = "# an integer of the length, or N/A"
Min_values = "None"
Max_values = "None"
Possible_categorical_Values = []
q_code = "q714"
old_ref = "None"
