[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[reference]
old_name = "reference"
Deduced_Data_Type = "Int64"

[formtype]
old_name = "formtype"
Deduced_Data_Type = "category"

[form_status]
old_name = "form_status"
Deduced_Data_Type = "category"

[instance]
old_name = "instance"
Deduced_Data_Type = "Int64"

[period]
old_name = "period"
Deduced_Data_Type = "Int64"

[employment]
old_name = "employment"
Deduced_Data_Type = "Int64"

[wowenterprisereference]
old_name = "wowenterprisereference"
Deduced_Data_Type = "Int64"

[rusic]
old_name = "rusic"
Deduced_Data_Type = "Int64"

[foreign_owner]
old_name = "ultfoc"
Deduced_Data_Type = "str"

[q200]
old_name = "200"
Deduced_Data_Type = "str"

[q201]
old_name = "201"
Deduced_Data_Type = "str"

[q202]
old_name = "202"
Deduced_Data_Type = "Int64"

[q203]
old_name = "203"
Deduced_Data_Type = "Int64"

[q204]
old_name = "204"
Deduced_Data_Type = "Int64"

[q205]
old_name = "205"
Deduced_Data_Type = "Int64"

[q206]
old_name = "206"
Deduced_Data_Type = "Int64"

[q207]
old_name = "207"
Deduced_Data_Type = "Int64"

[q209]
old_name = "209"
Deduced_Data_Type = "Int64"

[q210]
old_name = "210"
Deduced_Data_Type = "Int64"

[q211]
old_name = "211"
Deduced_Data_Type = "float64"

[q212]
old_name = "212"
Deduced_Data_Type = "Int64"

[q214]
old_name = "214"
Deduced_Data_Type = "Int64"

[q216]
old_name = "216"
Deduced_Data_Type = "Int64"

[q218]
old_name = "218"
Deduced_Data_Type = "Int64"

[q219]
old_name = "219"
Deduced_Data_Type = "Int64"

[q220]
old_name = "220"
Deduced_Data_Type = "Int64"

[q221]
old_name = "221"
Deduced_Data_Type = "Int64"

[q222]
old_name = "222"
Deduced_Data_Type = "Int64"

[q223]
old_name = "223"
Deduced_Data_Type = "Int64"

[q225]
old_name = "225"
Deduced_Data_Type = "Int64"

[q226]
old_name = "226"
Deduced_Data_Type = "Int64"

[q227]
old_name = "227"
Deduced_Data_Type = "Int64"

[q228]
old_name = "228"
Deduced_Data_Type = "Int64"

[q229]
old_name = "229"
Deduced_Data_Type = "Int64"

[q237]
old_name = "237"
Deduced_Data_Type = "Int64"

[q242]
old_name = "242"
Deduced_Data_Type = "Int64"

[q243]
old_name = "243"
Deduced_Data_Type = "Int64"

[q244]
old_name = "244"
Deduced_Data_Type = "Int64"

[q245]
old_name = "245"
Deduced_Data_Type = "Int64"

[q246]
old_name = "246"
Deduced_Data_Type = "Int64"

[q247]
old_name = "247"
Deduced_Data_Type = "Int64"

[q248]
old_name = "248"
Deduced_Data_Type = "Int64"

[q249]
old_name = "249"
Deduced_Data_Type = "Int64"

[q300]
old_name = "300"
Deduced_Data_Type = "object"

[q301]
old_name = "301"
Deduced_Data_Type = "Int64"

[q302]
old_name = "302"
Deduced_Data_Type = "Int64"

[q303]
old_name = "303"
Deduced_Data_Type = "Int64"

[q304]
old_name = "304"
Deduced_Data_Type = "Int64"

[q305]
old_name = "305"
Deduced_Data_Type = "float64"

[q250]
old_name = "250"
Deduced_Data_Type = "Int64"

[q251]
old_name = "251"
Deduced_Data_Type = "str"

[q307]
old_name = "307"
Deduced_Data_Type = "str"

[q308]
old_name = "308"
Deduced_Data_Type = "str"

[q309]
old_name = "309"
Deduced_Data_Type = "str"


["emp_researcher"]
old_name = ""
Deduced_Data_Type = "Int64"

["emp_technician"]
old_name = ""
Deduced_Data_Type = "Int64"

["emp_other"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_res_m"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_res_f"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_tec_m"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_tec_f"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_oth_m"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_oth_f"]
old_name = ""
Deduced_Data_Type = "Int64"

["emp_total"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_tot_m"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_tot_f"]
old_name = ""
Deduced_Data_Type = "Int64"

["headcount_total"]
old_name = ""
Deduced_Data_Type = "Int64"
