[freeze_id]
old_name = "freeze_id"
Deduced_Data_Type = "int64"

[period]
old_name = "period"
Deduced_Data_Type = "int64"

[period_year]
old_name = "period_year"
Deduced_Data_Type = "int64"

[cell_id]
old_name = "cell_id"
Deduced_Data_Type = "int64"

[sizeband]
old_name = "sizeband"
Deduced_Data_Type = "int64"

[civ_or_def]
old_name = "civ_or_def"
Deduced_Data_Type = "object"

[product_group]
old_name = "product_group"
Deduced_Data_Type = "object"

[ru_ref]
old_name = "ru_ref"
Deduced_Data_Type = "int64"

[period_contributor_id]
old_name = "period_contributor_id"
Deduced_Data_Type = "int64"

[form_type]
old_name = "form_type"
Deduced_Data_Type = "int64"

[form_status]
old_name = "form_status"
Deduced_Data_Type = "int64"

[data_source]
old_name = "data_source"
Deduced_Data_Type = "int64"

[employee_count]
old_name = "employee_count"
Deduced_Data_Type = "int64"

[wowentref]
old_name = "wowentref"
Deduced_Data_Type = "object"

[current_sic]
old_name = "current_sic"
Deduced_Data_Type = "int64"

[foreign_owner]
old_name = "foreign_owner"
Deduced_Data_Type = "object"

[emp_researcher]
old_name = "emp_researcher"
Deduced_Data_Type = "float64"

[emp_technician]
old_name = "emp_technician"
Deduced_Data_Type = "float64"

[emp_other]
old_name = "emp_other"
Deduced_Data_Type = "float64"

[emp_total]
old_name = "emp_total"
Deduced_Data_Type = "float64"

[q202]
old_name = "q202"
Deduced_Data_Type = "int64"

[q203]
old_name = "q203"
Deduced_Data_Type = "int64"

[q204]
old_name = "q204"
Deduced_Data_Type = "int64"

[q205]
old_name = "q205"
Deduced_Data_Type = "int64"

[q206]
old_name = "q206"
Deduced_Data_Type = "int64"

[q207]
old_name = "q207"
Deduced_Data_Type = "int64"

[q208]
old_name = "q208"
Deduced_Data_Type = "int64"

[q209]
old_name = "q209"
Deduced_Data_Type = "int64"

[q210]
old_name = "q210"
Deduced_Data_Type = "int64"

[q211]
old_name = "q211"
Deduced_Data_Type = "int64"

[q212]
old_name = "q212"
Deduced_Data_Type = "int64"

[q213]
old_name = "q213"
Deduced_Data_Type = "int64"

[q214]
old_name = "q214"
Deduced_Data_Type = "int64"

[q215]
old_name = "q215"
Deduced_Data_Type = "int64"

[q216]
old_name = "q216"
Deduced_Data_Type = "int64"

[q217]
old_name = "q217"
Deduced_Data_Type = "int64"

[q218]
old_name = "q218"
Deduced_Data_Type = "int64"

[q219]
old_name = "q219"
Deduced_Data_Type = "int64"

[q220]
old_name = "q220"
Deduced_Data_Type = "int64"

[q221]
old_name = "q221"
Deduced_Data_Type = "int64"

[q222]
old_name = "q222"
Deduced_Data_Type = "int64"

[q223]
old_name = "q223"
Deduced_Data_Type = "int64"

[q224]
old_name = "q224"
Deduced_Data_Type = "int64"

[q225]
old_name = "q225"
Deduced_Data_Type = "int64"

[q226]
old_name = "q226"
Deduced_Data_Type = "int64"

[q227]
old_name = "q227"
Deduced_Data_Type = "int64"

[q228]
old_name = "q228"
Deduced_Data_Type = "int64"

[q229]
old_name = "q229"
Deduced_Data_Type = "int64"

[q230]
old_name = "q230"
Deduced_Data_Type = "int64"

[q231]
old_name = "q231"
Deduced_Data_Type = "int64"

[q232]
old_name = "q232"
Deduced_Data_Type = "int64"

[q233]
old_name = "q233"
Deduced_Data_Type = "int64"

[q234]
old_name = "q234"
Deduced_Data_Type = "int64"

[q235]
old_name = "q235"
Deduced_Data_Type = "int64"

[q236]
old_name = "q236"
Deduced_Data_Type = "int64"

[q237]
old_name = "q237"
Deduced_Data_Type = "int64"

[q238]
old_name = "q238"
Deduced_Data_Type = "int64"

[q239]
old_name = "q239"
Deduced_Data_Type = "int64"

[q240]
old_name = "q240"
Deduced_Data_Type = "int64"

[q241]
old_name = "q241"
Deduced_Data_Type = "int64"

[q242]
old_name = "q242"
Deduced_Data_Type = "int64"

[q243]
old_name = "q243"
Deduced_Data_Type = "int64"

[q244]
old_name = "q244"
Deduced_Data_Type = "int64"

[q245]
old_name = "q245"
Deduced_Data_Type = "int64"

[q246]
old_name = "q246"
Deduced_Data_Type = "int64"

[q247]
old_name = "q247"
Deduced_Data_Type = "int64"

[q248]
old_name = "q248"
Deduced_Data_Type = "int64"

[q249]
old_name = "q249"
Deduced_Data_Type = "int64"

[q302]
old_name = "q302"
Deduced_Data_Type = "int64"

[q303]
old_name = "q303"
Deduced_Data_Type = "int64"

[q304]
old_name = "q304"
Deduced_Data_Type = "int64"

[q305]
old_name = "q305"
Deduced_Data_Type = "int64"

[headcount_res_m]
old_name = "headcount_res_m"
Deduced_Data_Type = "float64"

[headcount_res_f]
old_name = "headcount_res_f"
Deduced_Data_Type = "float64"

[headcount_tec_m]
old_name = "headcount_tec_m"
Deduced_Data_Type = "float64"

[headcount_tec_f]
old_name = "headcount_tec_f"
Deduced_Data_Type = "float64"

[headcount_oth_m]
old_name = "headcount_oth_m"
Deduced_Data_Type = "float64"

[headcount_oth_f]
old_name = "headcount_oth_f"
Deduced_Data_Type = "float64"

[headcount_total]
old_name = "headcount_total"
Deduced_Data_Type = "float64"

[q250]
old_name = "q250"
Deduced_Data_Type = "int64"

[q251]
old_name = "q251"
Deduced_Data_Type = "int64"

[q307]
old_name = "q307"
Deduced_Data_Type = "int64"

[q308]
old_name = "q308"
Deduced_Data_Type = "int64"

[q309]
old_name = "q309"
Deduced_Data_Type = "int64"

[q252]
old_name = "q252"
Deduced_Data_Type = "int64"

[q253]
old_name = "q253"
Deduced_Data_Type = "int64"

[q254]
old_name = "q254"
Deduced_Data_Type = "int64"

[q255]
old_name = "q255"
Deduced_Data_Type = "int64"

[q256]
old_name = "q256"
Deduced_Data_Type = "int64"

[q257]
old_name = "q257"
Deduced_Data_Type = "int64"

[q258 ]
old_name = "q258 "
Deduced_Data_Type = "int64"

