[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[reference]
old_name = "reference"
Deduced_Data_Type = "Int64"

[formtype]
old_name = "formtype"
Deduced_Data_Type = "category"

[form_status]
old_name = "form_status"
Deduced_Data_Type = "category"

[instance]
old_name = "instance"
Deduced_Data_Type = "Int64"

[period]
old_name = "period"
Deduced_Data_Type = "Int64"

[frozenemployment]
old_name = "frozenemployment"
Deduced_Data_Type = "Int64"

[wowenterprisereference]
old_name = "wowenterprisereference"
Deduced_Data_Type = "Int64"

[frozensic]
old_name = "frozensic"
Deduced_Data_Type = "Int64"

[foreign_owner]
old_name = "ultfoc"
Deduced_Data_Type = "str"

[200]
old_name = "200"
Deduced_Data_Type = "str"

[201]
old_name = "201"
Deduced_Data_Type = "str"

[202]
old_name = "202"
Deduced_Data_Type = "float64"

[203]
old_name = "203"
Deduced_Data_Type = "float64"

[204]
old_name = "204"
Deduced_Data_Type = "float64"

[205]
old_name = "205"
Deduced_Data_Type = "float64"

[206]
old_name = "206"
Deduced_Data_Type = "float64"

[207]
old_name = "207"
Deduced_Data_Type = "float64"

[209]
old_name = "209"
Deduced_Data_Type = "float64"

[210]
old_name = "210"
Deduced_Data_Type = "float64"

[211]
old_name = "211"
Deduced_Data_Type = "float64"

[212]
old_name = "212"
Deduced_Data_Type = "float64"

[214]
old_name = "214"
Deduced_Data_Type = "float64"

[216]
old_name = "216"
Deduced_Data_Type = "float64"

[218]
old_name = "218"
Deduced_Data_Type = "float64"

[219]
old_name = "219"
Deduced_Data_Type = "float64"

[220]
old_name = "220"
Deduced_Data_Type = "float64"

[221]
old_name = "221"
Deduced_Data_Type = "float64"

[222]
old_name = "222"
Deduced_Data_Type = "float64"

[223]
old_name = "223"
Deduced_Data_Type = "float64"

[225]
old_name = "225"
Deduced_Data_Type = "float64"

[226]
old_name = "226"
Deduced_Data_Type = "float64"

[227]
old_name = "227"
Deduced_Data_Type = "float64"

[228]
old_name = "228"
Deduced_Data_Type = "float64"

[229]
old_name = "229"
Deduced_Data_Type = "float64"

[237]
old_name = "237"
Deduced_Data_Type = "float64"

[242]
old_name = "242"
Deduced_Data_Type = "float64"

[243]
old_name = "243"
Deduced_Data_Type = "float64"

[244]
old_name = "244"
Deduced_Data_Type = "float64"

[245]
old_name = "245"
Deduced_Data_Type = "float64"

[246]
old_name = "246"
Deduced_Data_Type = "float64"

[247]
old_name = "247"
Deduced_Data_Type = "float64"

[248]
old_name = "248"
Deduced_Data_Type = "float64"

[249]
old_name = "249"
Deduced_Data_Type = "float64"

[300]
old_name = "300"
Deduced_Data_Type = "float64"

[301]
old_name = "301"
Deduced_Data_Type = "float64"

[302]
old_name = "302"
Deduced_Data_Type = "float64"

[303]
old_name = "303"
Deduced_Data_Type = "float64"

[304]
old_name = "304"
Deduced_Data_Type = "float64"

[305]
old_name = "305"
Deduced_Data_Type = "float64"

[405]
old_name = "405"
Deduced_Data_Type = "Int64"

[406]
old_name = "406"
Deduced_Data_Type = "Int64"

[407]
old_name = "407"
Deduced_Data_Type = "Int64"

[408]
old_name = "408"
Deduced_Data_Type = "Int64"

[409]
old_name = "409"
Deduced_Data_Type = "Int64"

[410]
old_name = "410"
Deduced_Data_Type = "Int64"

[411]
old_name = "411"
Deduced_Data_Type = "Int64"

[412]
old_name = "412"
Deduced_Data_Type = "Int64"

[501]
old_name = "501"
Deduced_Data_Type = "Int64"

[502]
old_name = "502"
Deduced_Data_Type = "Int64"

[503]
old_name = "503"
Deduced_Data_Type = "Int64"

[504]
old_name = "504"
Deduced_Data_Type = "Int64"

[505]
old_name = "505"
Deduced_Data_Type = "Int64"

[506]
old_name = "506"
Deduced_Data_Type = "Int64"

[507]
old_name = "507"
Deduced_Data_Type = "Int64"

[508]
old_name = "508"
Deduced_Data_Type = "Int64"

[250]
old_name = "250"
Deduced_Data_Type = "float64"

[251]
old_name = "251"
Deduced_Data_Type = "str"

[307]
old_name = "307"
Deduced_Data_Type = "float64"

[308]
old_name = "308"
Deduced_Data_Type = "float64"

[309]
old_name = "309"
Deduced_Data_Type = "float64"
