[reference]
old_name = "reference"
Deduced_Data_Type = "int64"

[instance]
old_name = "instance"
Deduced_Data_Type = "float64"

[101]
old_name = "101"
Deduced_Data_Type = "object"

[102]
old_name = "102"
Deduced_Data_Type = "float64"

[103]
old_name = "103"
Deduced_Data_Type = "float64"

[104]
old_name = "104"
Deduced_Data_Type = "float64"

[200]
old_name = "200"
Deduced_Data_Type = "object"

[201]
old_name = "201"
Deduced_Data_Type = "object"

[202]
old_name = "202"
Deduced_Data_Type = "float64"

[203]
old_name = "203"
Deduced_Data_Type = "float64"

[204]
old_name = "204"
Deduced_Data_Type = "float64"

[205]
old_name = "205"
Deduced_Data_Type = "float64"

[206]
old_name = "206"
Deduced_Data_Type = "float64"

[207]
old_name = "207"
Deduced_Data_Type = "float64"

[209]
old_name = "209"
Deduced_Data_Type = "float64"

[210]
old_name = "210"
Deduced_Data_Type = "float64"

[211]
old_name = "211"
Deduced_Data_Type = "float64"

[212]
old_name = "212"
Deduced_Data_Type = "float64"

[214]
old_name = "214"
Deduced_Data_Type = "float64"

[216]
old_name = "216"
Deduced_Data_Type = "float64"

[218]
old_name = "218"
Deduced_Data_Type = "float64"

[219]
old_name = "219"
Deduced_Data_Type = "float64"

[220]
old_name = "220"
Deduced_Data_Type = "float64"

[221]
old_name = "221"
Deduced_Data_Type = "float64"

[222]
old_name = "222"
Deduced_Data_Type = "float64"

[223]
old_name = "223"
Deduced_Data_Type = "float64"

[225]
old_name = "225"
Deduced_Data_Type = "float64"

[226]
old_name = "226"
Deduced_Data_Type = "float64"

[227]
old_name = "227"
Deduced_Data_Type = "float64"

[228]
old_name = "228"
Deduced_Data_Type = "float64"

[229]
old_name = "229"
Deduced_Data_Type = "float64"

[237]
old_name = "237"
Deduced_Data_Type = "float64"

[242]
old_name = "242"
Deduced_Data_Type = "float64"

[243]
old_name = "243"
Deduced_Data_Type = "float64"

[244]
old_name = "244"
Deduced_Data_Type = "float64"

[245]
old_name = "245"
Deduced_Data_Type = "float64"

[246]
old_name = "246"
Deduced_Data_Type = "float64"

[247]
old_name = "247"
Deduced_Data_Type = "float64"

[248]
old_name = "248"
Deduced_Data_Type = "float64"

[249]
old_name = "249"
Deduced_Data_Type = "float64"

[250]
old_name = "250"
Deduced_Data_Type = "float64"

[251]
old_name = "251"
Deduced_Data_Type = "float64"

[300]
old_name = "300"
Deduced_Data_Type = "float64"

[301]
old_name = "301"
Deduced_Data_Type = "float64"

[302]
old_name = "302"
Deduced_Data_Type = "float64"

[303]
old_name = "303"
Deduced_Data_Type = "float64"

[304]
old_name = "304"
Deduced_Data_Type = "float64"

[305]
old_name = "305"
Deduced_Data_Type = "float64"

[307]
old_name = "307"
Deduced_Data_Type = "float64"

[308]
old_name = "308"
Deduced_Data_Type = "float64"

[309]
old_name = "309"
Deduced_Data_Type = "float64"

[405]
old_name = "405"
Deduced_Data_Type = "float64"

[406]
old_name = "406"
Deduced_Data_Type = "float64"

[407]
old_name = "407"
Deduced_Data_Type = "float64"

[408]
old_name = "408"
Deduced_Data_Type = "float64"

[409]
old_name = "409"
Deduced_Data_Type = "float64"

[410]
old_name = "410"
Deduced_Data_Type = "float64"

[411]
old_name = "411"
Deduced_Data_Type = "float64"

[412]
old_name = "412"
Deduced_Data_Type = "float64"

[501]
old_name = "501"
Deduced_Data_Type = "float64"

[502]
old_name = "502"
Deduced_Data_Type = "float64"

[503]
old_name = "503"
Deduced_Data_Type = "float64"

[504]
old_name = "504"
Deduced_Data_Type = "float64"

[505]
old_name = "505"
Deduced_Data_Type = "float64"

[506]
old_name = "506"
Deduced_Data_Type = "float64"

[507]
old_name = "507"
Deduced_Data_Type = "float64"

[508]
old_name = "508"
Deduced_Data_Type = "float64"

[601]
old_name = "601"
Deduced_Data_Type = "float64"

[602]
old_name = "602"
Deduced_Data_Type = "float64"

[603]
old_name = "603"
Deduced_Data_Type = "float64"

[604]
old_name = "604"
Deduced_Data_Type = "object"

[605]
old_name = "605"
Deduced_Data_Type = "object"

[701]
old_name = "701"
Deduced_Data_Type = "float64"

[702]
old_name = "702"
Deduced_Data_Type = "float64"

[703]
old_name = "703"
Deduced_Data_Type = "float64"

[704]
old_name = "704"
Deduced_Data_Type = "float64"

[705]
old_name = "705"
Deduced_Data_Type = "float64"

[706]
old_name = "706"
Deduced_Data_Type = "float64"

[707]
old_name = "707"
Deduced_Data_Type = "float64"

[708]
old_name = "708"
Deduced_Data_Type = "object"

[709]
old_name = "709"
Deduced_Data_Type = "float64"

[710]
old_name = "710"
Deduced_Data_Type = "float64"

[711]
old_name = "711"
Deduced_Data_Type = "float64"

[712]
old_name = "712"
Deduced_Data_Type = "float64"

[713]
old_name = "713"
Deduced_Data_Type = "object"

[714]
old_name = "714"
Deduced_Data_Type = "object"

[9000]
old_name = "9000"
Deduced_Data_Type = "float64"

[9001]
old_name = "9001"
Deduced_Data_Type = "float64"

[9002]
old_name = "9002"
Deduced_Data_Type = "float64"

[9003]
old_name = "9003"
Deduced_Data_Type = "float64"

[9004]
old_name = "9004"
Deduced_Data_Type = "float64"

[9005]
old_name = "9005"
Deduced_Data_Type = "float64"

[9006]
old_name = "9006"
Deduced_Data_Type = "float64"

[9007]
old_name = "9007"
Deduced_Data_Type = "float64"

[9008]
old_name = "9008"
Deduced_Data_Type = "float64"

[9009]
old_name = "9009"
Deduced_Data_Type = "float64"

[9010]
old_name = "9010"
Deduced_Data_Type = "float64"

[9011]
old_name = "9011"
Deduced_Data_Type = "float64"

[9012]
old_name = "9012"
Deduced_Data_Type = "float64"

[9013]
old_name = "9013"
Deduced_Data_Type = "float64"

[period]
old_name = "period"
Deduced_Data_Type = "int64"

[survey]
old_name = "survey"
Deduced_Data_Type = "int64"

[formid]
old_name = "formid"
Deduced_Data_Type = "float64"

[status]
old_name = "status"
Deduced_Data_Type = "object"

[receiptdate]
old_name = "receiptdate"
Deduced_Data_Type = "object"

[lockedby]
old_name = "lockedby"
Deduced_Data_Type = "float64"

[lockeddate]
old_name = "lockeddate"
Deduced_Data_Type = "float64"

[formtype]
old_name = "formtype"
Deduced_Data_Type = "int64"

[checkletter]
old_name = "checkletter"
Deduced_Data_Type = "object"

[frozensicoutdated]
old_name = "frozensicoutdated"
Deduced_Data_Type = "int64"

[rusicoutdated]
old_name = "rusicoutdated"
Deduced_Data_Type = "int64"

[frozensic]
old_name = "frozensic"
Deduced_Data_Type = "int64"

[rusic]
old_name = "rusic"
Deduced_Data_Type = "int64"

[frozenemployees]
old_name = "frozenemployees"
Deduced_Data_Type = "int64"

[employees]
old_name = "employees"
Deduced_Data_Type = "int64"

[frozenemployment]
old_name = "frozenemployment"
Deduced_Data_Type = "int64"

[employment]
old_name = "employment"
Deduced_Data_Type = "int64"

[frozenfteemployment]
old_name = "frozenfteemployment"
Deduced_Data_Type = "float64"

[fteemployment]
old_name = "fteemployment"
Deduced_Data_Type = "float64"

[frozenturnover]
old_name = "frozenturnover"
Deduced_Data_Type = "int64"

[turnover]
old_name = "turnover"
Deduced_Data_Type = "int64"

[enterprisereference]
old_name = "enterprisereference"
Deduced_Data_Type = "int64"

[wowenterprisereference]
old_name = "wowenterprisereference"
Deduced_Data_Type = "int64"

[cellnumber]
old_name = "cellnumber"
Deduced_Data_Type = "int64"

[currency]
old_name = "currency"
Deduced_Data_Type = "object"

[vatreference]
old_name = "vatreference"
Deduced_Data_Type = "int64"

[payereference]
old_name = "payereference"
Deduced_Data_Type = "float64"

[companyregistrationnumber]
old_name = "companyregistrationnumber"
Deduced_Data_Type = "float64"

[numberlivelocalunits]
old_name = "numberlivelocalunits"
Deduced_Data_Type = "int64"

[numberlivevat]
old_name = "numberlivevat"
Deduced_Data_Type = "int64"

[numberlivepaye]
old_name = "numberlivepaye"
Deduced_Data_Type = "int64"

[legalstatus]
old_name = "legalstatus"
Deduced_Data_Type = "int64"

[reportingunitmarker]
old_name = "reportingunitmarker"
Deduced_Data_Type = "object"

[region]
old_name = "region"
Deduced_Data_Type = "object"

[birthdate]
old_name = "birthdate"
Deduced_Data_Type = "object"

[referencename]
old_name = "referencename"
Deduced_Data_Type = "object"

[referencepostcode]
old_name = "referencepostcode"
Deduced_Data_Type = "object"

[tradingstyle]
old_name = "tradingstyle"
Deduced_Data_Type = "object"

[selectiontype]
old_name = "selectiontype"
Deduced_Data_Type = "object"

[inclusionexclusion]
old_name = "inclusionexclusion"
Deduced_Data_Type = "float64"

[lastupdateddate]
old_name = "lastupdateddate"
Deduced_Data_Type = "object"

[statusencoded]
old_name = "statusencoded"
Deduced_Data_Type = "category"

[postcodes_harmonised]
old_name = "postcodes_harmonised"
Deduced_Data_Type = "object"

[emp_researcher]
old_name = "emp_researcher"
Deduced_Data_Type = "float64"

[emp_technician]
old_name = "emp_technician"
Deduced_Data_Type = "float64"

[emp_other]
old_name = "emp_other"
Deduced_Data_Type = "float64"

[emp_total]
old_name = "emp_total"
Deduced_Data_Type = "float64"

[headcount_res_m]
old_name = "headcount_res_m"
Deduced_Data_Type = "float64"

[headcount_res_f]
old_name = "headcount_res_f"
Deduced_Data_Type = "float64"

[headcount_tec_m]
old_name = "headcount_tec_m"
Deduced_Data_Type = "float64"

[headcount_tec_f]
old_name = "headcount_tec_f"
Deduced_Data_Type = "float64"

[headcount_oth_m]
old_name = "headcount_oth_m"
Deduced_Data_Type = "float64"

[headcount_oth_f]
old_name = "headcount_oth_f"
Deduced_Data_Type = "float64"

[headcount_tot_m]
old_name = "headcount_tot_m"
Deduced_Data_Type = "float64"

[headcount_tot_f]
old_name = "headcount_tot_f"
Deduced_Data_Type = "float64"

[headcount_total]
old_name = "headcount_total"
Deduced_Data_Type = "float64"

[imp_marker]
old_name = "imp_marker"
Deduced_Data_Type = "object"

[211_imputed]
old_name = "211_imputed"
Deduced_Data_Type = "float64"

[305_imputed]
old_name = "305_imputed"
Deduced_Data_Type = "float64"

[emp_researcher_imputed]
old_name = "emp_researcher_imputed"
Deduced_Data_Type = "float64"

[emp_technician_imputed]
old_name = "emp_technician_imputed"
Deduced_Data_Type = "float64"

[emp_other_imputed]
old_name = "emp_other_imputed"
Deduced_Data_Type = "float64"

[headcount_res_m_imputed]
old_name = "headcount_res_m_imputed"
Deduced_Data_Type = "float64"

[headcount_res_f_imputed]
old_name = "headcount_res_f_imputed"
Deduced_Data_Type = "float64"

[headcount_tec_m_imputed]
old_name = "headcount_tec_m_imputed"
Deduced_Data_Type = "float64"

[headcount_tec_f_imputed]
old_name = "headcount_tec_f_imputed"
Deduced_Data_Type = "float64"

[headcount_oth_m_imputed]
old_name = "headcount_oth_m_imputed"
Deduced_Data_Type = "float64"

[headcount_oth_f_imputed]
old_name = "headcount_oth_f_imputed"
Deduced_Data_Type = "float64"

[202_imputed]
old_name = "202_imputed"
Deduced_Data_Type = "float64"

[203_imputed]
old_name = "203_imputed"
Deduced_Data_Type = "float64"

[204_imputed]
old_name = "204_imputed"
Deduced_Data_Type = "float64"

[205_imputed]
old_name = "205_imputed"
Deduced_Data_Type = "float64"

[206_imputed]
old_name = "206_imputed"
Deduced_Data_Type = "float64"

[207_imputed]
old_name = "207_imputed"
Deduced_Data_Type = "float64"

[209_imputed]
old_name = "209_imputed"
Deduced_Data_Type = "float64"

[210_imputed]
old_name = "210_imputed"
Deduced_Data_Type = "float64"

[212_imputed]
old_name = "212_imputed"
Deduced_Data_Type = "float64"

[214_imputed]
old_name = "214_imputed"
Deduced_Data_Type = "float64"

[216_imputed]
old_name = "216_imputed"
Deduced_Data_Type = "float64"

[218_imputed]
old_name = "218_imputed"
Deduced_Data_Type = "float64"

[219_imputed]
old_name = "219_imputed"
Deduced_Data_Type = "float64"

[220_imputed]
old_name = "220_imputed"
Deduced_Data_Type = "float64"

[221_imputed]
old_name = "221_imputed"
Deduced_Data_Type = "float64"

[222_imputed]
old_name = "222_imputed"
Deduced_Data_Type = "float64"

[223_imputed]
old_name = "223_imputed"
Deduced_Data_Type = "float64"

[225_imputed]
old_name = "225_imputed"
Deduced_Data_Type = "float64"

[226_imputed]
old_name = "226_imputed"
Deduced_Data_Type = "float64"

[227_imputed]
old_name = "227_imputed"
Deduced_Data_Type = "float64"

[228_imputed]
old_name = "228_imputed"
Deduced_Data_Type = "float64"

[229_imputed]
old_name = "229_imputed"
Deduced_Data_Type = "float64"

[237_imputed]
old_name = "237_imputed"
Deduced_Data_Type = "float64"

[242_imputed]
old_name = "242_imputed"
Deduced_Data_Type = "float64"

[243_imputed]
old_name = "243_imputed"
Deduced_Data_Type = "float64"

[244_imputed]
old_name = "244_imputed"
Deduced_Data_Type = "float64"

[245_imputed]
old_name = "245_imputed"
Deduced_Data_Type = "float64"

[246_imputed]
old_name = "246_imputed"
Deduced_Data_Type = "float64"

[247_imputed]
old_name = "247_imputed"
Deduced_Data_Type = "float64"

[248_imputed]
old_name = "248_imputed"
Deduced_Data_Type = "float64"

[249_imputed]
old_name = "249_imputed"
Deduced_Data_Type = "float64"

[250_imputed]
old_name = "250_imputed"
Deduced_Data_Type = "float64"

[302_imputed]
old_name = "302_imputed"
Deduced_Data_Type = "float64"

[303_imputed]
old_name = "303_imputed"
Deduced_Data_Type = "float64"

[304_imputed]
old_name = "304_imputed"
Deduced_Data_Type = "float64"

[emp_total_imputed]
old_name = "emp_total_imputed"
Deduced_Data_Type = "float64"

[headcount_tot_m_imputed]
old_name = "headcount_tot_m_imputed"
Deduced_Data_Type = "float64"

[headcount_tot_f_imputed]
old_name = "headcount_tot_f_imputed"
Deduced_Data_Type = "float64"

[headcount_total_imputed]
old_name = "headcount_total_imputed"
Deduced_Data_Type = "float64"

[imp_class]
old_name = "imp_class"
Deduced_Data_Type = "object"

[202_prev]
old_name = "202_prev"
Deduced_Data_Type = "float64"

[203_prev]
old_name = "203_prev"
Deduced_Data_Type = "float64"

[204_prev]
old_name = "204_prev"
Deduced_Data_Type = "float64"

[205_prev]
old_name = "205_prev"
Deduced_Data_Type = "float64"

[206_prev]
old_name = "206_prev"
Deduced_Data_Type = "float64"

[207_prev]
old_name = "207_prev"
Deduced_Data_Type = "float64"

[209_prev]
old_name = "209_prev"
Deduced_Data_Type = "float64"

[210_prev]
old_name = "210_prev"
Deduced_Data_Type = "float64"

[211_prev]
old_name = "211_prev"
Deduced_Data_Type = "float64"

[212_prev]
old_name = "212_prev"
Deduced_Data_Type = "float64"

[214_prev]
old_name = "214_prev"
Deduced_Data_Type = "float64"

[216_prev]
old_name = "216_prev"
Deduced_Data_Type = "float64"

[218_prev]
old_name = "218_prev"
Deduced_Data_Type = "float64"

[219_prev]
old_name = "219_prev"
Deduced_Data_Type = "float64"

[220_prev]
old_name = "220_prev"
Deduced_Data_Type = "float64"

[221_prev]
old_name = "221_prev"
Deduced_Data_Type = "float64"

[222_prev]
old_name = "222_prev"
Deduced_Data_Type = "float64"

[223_prev]
old_name = "223_prev"
Deduced_Data_Type = "float64"

[225_prev]
old_name = "225_prev"
Deduced_Data_Type = "float64"

[226_prev]
old_name = "226_prev"
Deduced_Data_Type = "float64"

[227_prev]
old_name = "227_prev"
Deduced_Data_Type = "float64"

[228_prev]
old_name = "228_prev"
Deduced_Data_Type = "float64"

[229_prev]
old_name = "229_prev"
Deduced_Data_Type = "float64"

[237_prev]
old_name = "237_prev"
Deduced_Data_Type = "float64"

[242_prev]
old_name = "242_prev"
Deduced_Data_Type = "float64"

[243_prev]
old_name = "243_prev"
Deduced_Data_Type = "float64"

[244_prev]
old_name = "244_prev"
Deduced_Data_Type = "float64"

[245_prev]
old_name = "245_prev"
Deduced_Data_Type = "float64"

[246_prev]
old_name = "246_prev"
Deduced_Data_Type = "float64"

[247_prev]
old_name = "247_prev"
Deduced_Data_Type = "float64"

[248_prev]
old_name = "248_prev"
Deduced_Data_Type = "float64"

[249_prev]
old_name = "249_prev"
Deduced_Data_Type = "float64"

[250_prev]
old_name = "250_prev"
Deduced_Data_Type = "float64"

[302_prev]
old_name = "302_prev"
Deduced_Data_Type = "float64"

[303_prev]
old_name = "303_prev"
Deduced_Data_Type = "float64"

[304_prev]
old_name = "304_prev"
Deduced_Data_Type = "float64"

[305_prev]
old_name = "305_prev"
Deduced_Data_Type = "float64"

[emp_researcher_prev]
old_name = "emp_researcher_prev"
Deduced_Data_Type = "float64"

[emp_technician_prev]
old_name = "emp_technician_prev"
Deduced_Data_Type = "float64"

[emp_other_prev]
old_name = "emp_other_prev"
Deduced_Data_Type = "float64"

[emp_total_prev]
old_name = "emp_total_prev"
Deduced_Data_Type = "float64"

[headcount_res_m_prev]
old_name = "headcount_res_m_prev"
Deduced_Data_Type = "float64"

[headcount_res_f_prev]
old_name = "headcount_res_f_prev"
Deduced_Data_Type = "float64"

[headcount_tec_m_prev]
old_name = "headcount_tec_m_prev"
Deduced_Data_Type = "float64"

[headcount_tec_f_prev]
old_name = "headcount_tec_f_prev"
Deduced_Data_Type = "float64"

[headcount_oth_m_prev]
old_name = "headcount_oth_m_prev"
Deduced_Data_Type = "float64"

[headcount_oth_f_prev]
old_name = "headcount_oth_f_prev"
Deduced_Data_Type = "float64"

[headcount_tot_m_prev]
old_name = "headcount_tot_m_prev"
Deduced_Data_Type = "float64"

[headcount_tot_f_prev]
old_name = "headcount_tot_f_prev"
Deduced_Data_Type = "float64"

[headcount_total_prev]
old_name = "headcount_total_prev"
Deduced_Data_Type = "float64"

[211_link]
old_name = "211_link"
Deduced_Data_Type = "float64"

[305_link]
old_name = "305_link"
Deduced_Data_Type = "float64"

[emp_researcher_link]
old_name = "emp_researcher_link"
Deduced_Data_Type = "float64"

[emp_technician_link]
old_name = "emp_technician_link"
Deduced_Data_Type = "float64"

[emp_other_link]
old_name = "emp_other_link"
Deduced_Data_Type = "float64"

[headcount_res_m_link]
old_name = "headcount_res_m_link"
Deduced_Data_Type = "float64"

[headcount_res_f_link]
old_name = "headcount_res_f_link"
Deduced_Data_Type = "float64"

[headcount_tec_m_link]
old_name = "headcount_tec_m_link"
Deduced_Data_Type = "float64"

[headcount_tec_f_link]
old_name = "headcount_tec_f_link"
Deduced_Data_Type = "float64"

[headcount_oth_m_link]
old_name = "headcount_oth_m_link"
Deduced_Data_Type = "float64"

[headcount_oth_f_link]
old_name = "headcount_oth_f_link"
Deduced_Data_Type = "float64"

[200_original]
old_name = "200_original"
Deduced_Data_Type = "float64"

[pg_sic_class]
old_name = "pg_sic_class"
Deduced_Data_Type = "object"

[empty_pgsic_group]
old_name = "empty_pgsic_group"
Deduced_Data_Type = "object"

[empty_pg_group]
old_name = "empty_pg_group"
Deduced_Data_Type = "object"

[200_imp_marker]
old_name = "200_imp_marker"
Deduced_Data_Type = "object"

[211_trim]
old_name = "211_trim"
Deduced_Data_Type = "object"

[305_trim]
old_name = "305_trim"
Deduced_Data_Type = "object"
