["Area Code (ITL1)"]
old_name = None
Deduced_Data_Type = "str"

["Country or region (ITL1)"]
old_name = None
Deduced_Data_Type = "str"

["2023"]
old_name = None
Deduced_Data_Type = "float64"

["Notes"]
old_name = None
Deduced_Data_Type = "str"
