[reference]
old_name = "reference"
Deduced_Data_Type = "int64"

[instance]
old_name = "instance"
Deduced_Data_Type = "float64"

[200]
old_name = "200"
Deduced_Data_Type = "object"

[201]
old_name = "201"
Deduced_Data_Type = "object"

[202]
old_name = "202"
Deduced_Data_Type = "float64"

[203]
old_name = "203"
Deduced_Data_Type = "float64"

[204]
old_name = "204"
Deduced_Data_Type = "float64"

[205]
old_name = "205"
Deduced_Data_Type = "float64"

[206]
old_name = "206"
Deduced_Data_Type = "float64"

[207]
old_name = "207"
Deduced_Data_Type = "float64"

[209]
old_name = "209"
Deduced_Data_Type = "float64"

[210]
old_name = "210"
Deduced_Data_Type = "float64"

[211]
old_name = "211"
Deduced_Data_Type = "float64"

[212]
old_name = "212"
Deduced_Data_Type = "float64"

[214]
old_name = "214"
Deduced_Data_Type = "float64"

[216]
old_name = "216"
Deduced_Data_Type = "float64"

[218]
old_name = "218"
Deduced_Data_Type = "float64"

[219]
old_name = "219"
Deduced_Data_Type = "float64"

[220]
old_name = "220"
Deduced_Data_Type = "float64"

[221]
old_name = "221"
Deduced_Data_Type = "float64"

[222]
old_name = "222"
Deduced_Data_Type = "float64"

[223]
old_name = "223"
Deduced_Data_Type = "float64"

[225]
old_name = "225"
Deduced_Data_Type = "float64"

[226]
old_name = "226"
Deduced_Data_Type = "float64"

[227]
old_name = "227"
Deduced_Data_Type = "float64"

[228]
old_name = "228"
Deduced_Data_Type = "float64"

[229]
old_name = "229"
Deduced_Data_Type = "float64"

[237]
old_name = "237"
Deduced_Data_Type = "float64"

[242]
old_name = "242"
Deduced_Data_Type = "float64"

[243]
old_name = "243"
Deduced_Data_Type = "float64"

[244]
old_name = "244"
Deduced_Data_Type = "float64"

[245]
old_name = "245"
Deduced_Data_Type = "float64"

[246]
old_name = "246"
Deduced_Data_Type = "float64"

[247]
old_name = "247"
Deduced_Data_Type = "float64"

[248]
old_name = "248"
Deduced_Data_Type = "float64"

[249]
old_name = "249"
Deduced_Data_Type = "float64"

[250]
old_name = "250"
Deduced_Data_Type = "float64"

[251]
old_name = "251"
Deduced_Data_Type = "float64"

[300]
old_name = "300"
Deduced_Data_Type = "float64"

[301]
old_name = "301"
Deduced_Data_Type = "float64"

[302]
old_name = "302"
Deduced_Data_Type = "float64"

[303]
old_name = "303"
Deduced_Data_Type = "float64"

[304]
old_name = "304"
Deduced_Data_Type = "float64"

[305]
old_name = "305"
Deduced_Data_Type = "float64"

[307]
old_name = "307"
Deduced_Data_Type = "float64"

[308]
old_name = "308"
Deduced_Data_Type = "float64"

[309]
old_name = "309"
Deduced_Data_Type = "float64"

[status]
old_name = "status"
Deduced_Data_Type = "object"

[formtype]
old_name = "formtype"
Deduced_Data_Type = "int64"

[rusic]
old_name = "rusic"
Deduced_Data_Type = "int64"

[employment]
old_name = "employment"
Deduced_Data_Type = "int64"

[cellnumber]
old_name = "cellnumber"
Deduced_Data_Type = "int64"

[referencename]
old_name = "referencename"
Deduced_Data_Type = "object"

[selectiontype]
old_name = "selectiontype"
Deduced_Data_Type = "object"

[statusencoded]
old_name = "statusencoded"
Deduced_Data_Type = "int64"

[postcodes_harmonised]
old_name = "postcodes_harmonised"
Deduced_Data_Type = "object"

[emp_researcher]
old_name = "emp_researcher"
Deduced_Data_Type = "float64"

[emp_technician]
old_name = "emp_technician"
Deduced_Data_Type = "float64"

[emp_other]
old_name = "emp_other"
Deduced_Data_Type = "float64"

[emp_total]
old_name = "emp_total"
Deduced_Data_Type = "float64"

[headcount_res_m]
old_name = "headcount_res_m"
Deduced_Data_Type = "float64"

[headcount_res_f]
old_name = "headcount_res_f"
Deduced_Data_Type = "float64"

[headcount_tec_m]
old_name = "headcount_tec_m"
Deduced_Data_Type = "float64"

[headcount_tec_f]
old_name = "headcount_tec_f"
Deduced_Data_Type = "float64"

[headcount_oth_m]
old_name = "headcount_oth_m"
Deduced_Data_Type = "float64"

[headcount_oth_f]
old_name = "headcount_oth_f"
Deduced_Data_Type = "float64"

[headcount_tot_m]
old_name = "headcount_tot_m"
Deduced_Data_Type = "float64"

[headcount_tot_f]
old_name = "headcount_tot_f"
Deduced_Data_Type = "float64"

[headcount_total]
old_name = "headcount_total"
Deduced_Data_Type = "float64"

[imp_marker]
old_name = "imp_marker"
Deduced_Data_Type = "object"

[211_imputed]
old_name = "211_imputed"
Deduced_Data_Type = "float64"

[305_imputed]
old_name = "305_imputed"
Deduced_Data_Type = "float64"

[emp_researcher_imputed]
old_name = "emp_researcher_imputed"
Deduced_Data_Type = "float64"

[emp_technician_imputed]
old_name = "emp_technician_imputed"
Deduced_Data_Type = "float64"

[emp_other_imputed]
old_name = "emp_other_imputed"
Deduced_Data_Type = "float64"

[headcount_res_m_imputed]
old_name = "headcount_res_m_imputed"
Deduced_Data_Type = "float64"

[headcount_res_f_imputed]
old_name = "headcount_res_f_imputed"
Deduced_Data_Type = "float64"

[headcount_tec_m_imputed]
old_name = "headcount_tec_m_imputed"
Deduced_Data_Type = "float64"

[headcount_tec_f_imputed]
old_name = "headcount_tec_f_imputed"
Deduced_Data_Type = "float64"

[headcount_oth_m_imputed]
old_name = "headcount_oth_m_imputed"
Deduced_Data_Type = "float64"

[headcount_oth_f_imputed]
old_name = "headcount_oth_f_imputed"
Deduced_Data_Type = "float64"

[202_imputed]
old_name = "202_imputed"
Deduced_Data_Type = "float64"

[203_imputed]
old_name = "203_imputed"
Deduced_Data_Type = "float64"

[204_imputed]
old_name = "204_imputed"
Deduced_Data_Type = "float64"

[205_imputed]
old_name = "205_imputed"
Deduced_Data_Type = "float64"

[206_imputed]
old_name = "206_imputed"
Deduced_Data_Type = "float64"

[207_imputed]
old_name = "207_imputed"
Deduced_Data_Type = "float64"

[209_imputed]
old_name = "209_imputed"
Deduced_Data_Type = "float64"

[210_imputed]
old_name = "210_imputed"
Deduced_Data_Type = "float64"

[212_imputed]
old_name = "212_imputed"
Deduced_Data_Type = "float64"

[214_imputed]
old_name = "214_imputed"
Deduced_Data_Type = "float64"

[216_imputed]
old_name = "216_imputed"
Deduced_Data_Type = "float64"

[218_imputed]
old_name = "218_imputed"
Deduced_Data_Type = "float64"

[219_imputed]
old_name = "219_imputed"
Deduced_Data_Type = "float64"

[220_imputed]
old_name = "220_imputed"
Deduced_Data_Type = "float64"

[221_imputed]
old_name = "221_imputed"
Deduced_Data_Type = "float64"

[222_imputed]
old_name = "222_imputed"
Deduced_Data_Type = "float64"

[223_imputed]
old_name = "223_imputed"
Deduced_Data_Type = "float64"

[225_imputed]
old_name = "225_imputed"
Deduced_Data_Type = "float64"

[226_imputed]
old_name = "226_imputed"
Deduced_Data_Type = "float64"

[227_imputed]
old_name = "227_imputed"
Deduced_Data_Type = "float64"

[228_imputed]
old_name = "228_imputed"
Deduced_Data_Type = "float64"

[229_imputed]
old_name = "229_imputed"
Deduced_Data_Type = "float64"

[237_imputed]
old_name = "237_imputed"
Deduced_Data_Type = "float64"

[242_imputed]
old_name = "242_imputed"
Deduced_Data_Type = "float64"

[243_imputed]
old_name = "243_imputed"
Deduced_Data_Type = "float64"

[244_imputed]
old_name = "244_imputed"
Deduced_Data_Type = "float64"

[245_imputed]
old_name = "245_imputed"
Deduced_Data_Type = "float64"

[246_imputed]
old_name = "246_imputed"
Deduced_Data_Type = "float64"

[247_imputed]
old_name = "247_imputed"
Deduced_Data_Type = "float64"

[248_imputed]
old_name = "248_imputed"
Deduced_Data_Type = "float64"

[249_imputed]
old_name = "249_imputed"
Deduced_Data_Type = "float64"

[250_imputed]
old_name = "250_imputed"
Deduced_Data_Type = "float64"

[302_imputed]
old_name = "302_imputed"
Deduced_Data_Type = "float64"

[303_imputed]
old_name = "303_imputed"
Deduced_Data_Type = "float64"

[304_imputed]
old_name = "304_imputed"
Deduced_Data_Type = "float64"

[emp_total_imputed]
old_name = "emp_total_imputed"
Deduced_Data_Type = "float64"

[headcount_tot_m_imputed]
old_name = "headcount_tot_m_imputed"
Deduced_Data_Type = "float64"

[headcount_tot_f_imputed]
old_name = "headcount_tot_f_imputed"
Deduced_Data_Type = "float64"

[headcount_total_imputed]
old_name = "headcount_total_imputed"
Deduced_Data_Type = "float64"

[imp_class]
old_name = "imp_class"
Deduced_Data_Type = "object"


[211_trim]
old_name = "211_trim"
Deduced_Data_Type = "float64"

[305_trim]
old_name = "305_trim"
Deduced_Data_Type = "float64"

[emp_researcher_trim]
old_name = "emp_researcher_trim"
Deduced_Data_Type = "float64"

[emp_technician_trim]
old_name = "emp_technician_trim"
Deduced_Data_Type = "float64"

[emp_other_trim]
old_name = "emp_other_trim"
Deduced_Data_Type = "float64"

[headcount_res_m_trim]
old_name = "headcount_res_m_trim"
Deduced_Data_Type = "float64"

[headcount_res_f_trim]
old_name = "headcount_res_f_trim"
Deduced_Data_Type = "float64"

[headcount_tec_m_trim]
old_name = "headcount_tec_m_trim"
Deduced_Data_Type = "float64"

[headcount_tec_f_trim]
old_name = "headcount_tec_f_trim"
Deduced_Data_Type = "float64"

[headcount_oth_m_trim]
old_name = "headcount_oth_m_trim"
Deduced_Data_Type = "float64"

[headcount_oth_f_trim]
old_name = "headcount_oth_f_trim"
Deduced_Data_Type = "float64"

[emp_total_trim]
old_name = "emp_total_trim"
Deduced_Data_Type = "float64"

[headcount_total_trim]
old_name = "headcount_total_trim"
Deduced_Data_Type = "float64"

[manual_trim]
old_name = "manual_trim"
Deduced_Data_Type = "boolean"
