[period_year]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[ru_ref]
old_name = "reference"
Deduced_Data_Type = "Int64"

[form_type]
old_name = "formtype"
Deduced_Data_Type = "str"

[form_status]
old_name = "form_status"
Deduced_Data_Type = "category"

[ua_county]
old_name = "itl"
Deduced_Data_Type = "str"

[employee_count]
old_name = "employment"
Deduced_Data_Type = "Int64"

[wowentref]
old_name = "wowenterprisereference"
Deduced_Data_Type = "Int64"

[current_sic]
old_name = "rusic"
Deduced_Data_Type = "Int64"

[foreign_owner]
old_name = "ultfoc"
Deduced_Data_Type = "str"

[product_group]
old_name = "201"
Deduced_Data_Type = "str"

[sizeband]
old_name = "sizeband"
Deduced_Data_Type = "float64"

[q604]
old_name = "604"
Deduced_Data_Type = "str"

[q605]
old_name = "605"
Deduced_Data_Type = "str"

[q701]
old_name = "701"
Deduced_Data_Type = "float64"

[q702]
old_name = "702"
Deduced_Data_Type = "float64"

[q703]
old_name = "703"
Deduced_Data_Type = "float64"

[q704]
old_name = "704"
Deduced_Data_Type = "float64"

[q705]
old_name = "705"
Deduced_Data_Type = "float64"

[q706]
old_name = "706"
Deduced_Data_Type = "float64"

[q707]
old_name = "707"
Deduced_Data_Type = "float64"

[headcount_civil]
old_name = "headcount_civil"
Deduced_Data_Type = "float64"

[headcount_defence]
old_name = "headcount_defence"
Deduced_Data_Type = "float64"

[post_code]
old_name = "601"
Deduced_Data_Type = "str"

[q713]
old_name = "713"
Deduced_Data_Type = "str"

[q714]
old_name = "714"
Deduced_Data_Type = "str"
