[ref]
old_name = "reference"
Deduced_Data_Type = "Int64"

[period]
old_name = "period_year"
Deduced_Data_Type = "Int64"

[entref]
old_name = "enterprisereference"
Deduced_Data_Type = "Int64"

[wow]
old_name = "wowenterprisereference"
Deduced_Data_Type = "Int64"

[selgrpno]
old_name = "pg_numeric"
Deduced_Data_Type = "str"

[sic07]
old_name = "rusic"
Deduced_Data_Type = "Int64"

[form]
old_name = "formtype"
Deduced_Data_Type = "str"

[emp]
old_name = "employment"
Deduced_Data_Type = "Int64"

[turn]
old_name = "frozenturnover"
Deduced_Data_Type = "Int64"

[f_owner]
old_name = "ultfoc"
Deduced_Data_Type = "str"

[sizebd]
old_name = "sizeband"
Deduced_Data_Type = "Int64"

[rec_mkr]
old_name = "form_status"
Deduced_Data_Type = "Int64"

[reg_code]
old_name = "itl"
Deduced_Data_Type = "str"

[percent]
old_name = "602"
Deduced_Data_Type = "float64"

[rtngrpno]
old_name = "201"
Deduced_Data_Type = "str"

[c_or_d]
old_name = "200"
Deduced_Data_Type = "str"

[emp_res]
old_name = "emp_researcher"
Deduced_Data_Type = "float64"

[emp_tech]
old_name = "emp_technician"
Deduced_Data_Type = "float64"

[emp_oth]
old_name = "emp_other"
Deduced_Data_Type = "float64"

[slries]
old_name = "202"
Deduced_Data_Type ="Int64"

[curr_oth]
old_name = "203"
Deduced_Data_Type ="Int64"

[curr_tot]
old_name = "204"
Deduced_Data_Type ="Int64"

[res_bas]
old_name = "205"
Deduced_Data_Type ="Int64"

[res_app]
old_name = "206"
Deduced_Data_Type ="Int64"

[experm]
old_name = "207"
Deduced_Data_Type ="Int64"

[c_lnd_bl]
old_name = "C_lnd_bl"
Deduced_Data_Type = "Int64"

[cxplm]
old_name = "209"
Deduced_Data_Type ="Int64"

[intram]
old_name = "211"
Deduced_Data_Type ="Int64"

[ctrl_gv]
old_name = "214"
Deduced_Data_Type ="Int64"

[priv]
old_name = "216"
Deduced_Data_Type ="Int64"

[ovss_oth]
old_name = "ovss_oth"
Deduced_Data_Type ="Int64"

[own_f]
old_name = "212"
Deduced_Data_Type ="Int64"

[oth_sc]
old_name = "oth_sc"
Deduced_Data_Type ="Int64"

[f_tot]
old_name = "218"
Deduced_Data_Type ="Int64"

[ex_uk]
old_name = "302"
Deduced_Data_Type ="Int64"

[ex_uk_gv]
old_name = "303"
Deduced_Data_Type ="Int64"

[ex_uk_b]
old_name = "304"
Deduced_Data_Type ="Int64"

[ex_total]
old_name = "305"
Deduced_Data_Type ="Int64"

[a_weight]
old_name = "a_weight"
Deduced_Data_Type = "float64"
