config_validation:
  validate: True
  path: src/dev_config_schema.yaml
global:
  # Logging settings
  log_to_file: True # Write logs to .log file
  logging_level: "DEBUG"
  table_config: "SingleLine"
  # Environment settings
  dev_test : False
  network_or_hdfs: "network" #whether to load from hdfs or network (local Python)
  # Construction Settings
  load_reference_list: True # the reference list corrections should always be loaded in year 1
  load_from_feather: True
  # Apportionment to sites settings
  apportion_sites: True
runlog_writer:
  write_csv: True # Write the runlog to a CSV file
  write_hdf5: False # Write the runlog to an HDF5 file
  write_sql: False # Write the runlog to a SQL database
  display: False # Display the runlog in the terminal
  log_path: "/ons/rdbe_dev/"
hdfs_paths:
  logs_foldername: "/ons/rdbe_dev/logs/run_logs"
modules:
  staging: "01_staging"
  freezing: "02_freezing"
  northern_ireland: "03_northern_ireland"
  construction: "04_construction"
  mapping: "05_mapping"
  imputation: "06_imputation"
  outliers: "07_outliers"
  estimation: "08_estimation"
  apportionment: "09_apportionment"
  outputs: "10_outputs"
qa_paths:
  feather_output: "01_staging/feather"
  staging_output_path: "01_staging/staging_qa/full_responses_qa"
  postcode_path: "01_staging/staging_qa/postcode_validation"
  ni_staging_output_path: "02_northern_ireland/ni_staging_qa"
  imputation_path:  "imputation"
  estimation_path:  "estimation"
  apportionment_path:  "apportionment"
  output_path:  "outputs"
  export_path: "outgoing_export"
network_paths:
  root: "R:/BERD Results System Development 2023/DAP_emulation/"
  logs_foldername: "logs/run_logs" # dev config
  snapshot_path: "survey_return_data/snapshot-202212-002-83b5bacd-7c99-45cf-b989-d43d762dd054.json"
  secondary_snapshot_path: "berd_survey/anonymised/v1/snapshot-202012-002-fba5c4ba-fb8c-4a62-87bb-66c725eea5fd.json" # TODO Check if this works
  ni_full_responses_path: "northern_ireland/2021/TEST_ni.csv" # TESTER FILE
  history_path: "BERD_V7_Anonymised" #"R:\BERD Results System Development 2023\DAP_emulation\backseries\v1"
  # Imputation and outliers input paths
  backdata_path: "R:/BERD Results System Development 2023/2021_data/validation-extract-responses-202112.csv"
  manual_imp_trim_path: "imputation/manual_trimming/trimming_qa_2023-11-27_v359.csv"
  manual_outliers_path: "outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  outliers_path: "outliers"
  # Construction paths
  construction_file_path: "construction/manual_construction/test_construction_file.csv"
  construction_file_path_ni: "construction/manual_construction/test_construction_ni_file.csv"
  # postcode paths
  postcode_masterlist: "ONS_Postcode_Reference/postcodes_pcd2_itl.csv"
  # mapper paths
  mappers_version: "v1"
  ultfoc_mapper_path: "mappers/2023/BERD_2022_ultfoc.csv"
  itl_mapper_path: 'mappers/2023/itl_6162_ni.csv'
  cellno_2022_path: 'mappers/2023/berd_2022_cellno_coverage.csv'
  sic_pg_alpha_mapper_path: 'mappers/sic_pg_alpha.csv'
  sic_pg_utf_mapper_path: 'mappers/SIC_to_PG_UTF-8.csv'
  pg_detailed_mapper_path: "mappers/pg_detailed.csv"
  pg_num_alpha_mapper_path: 'mappers/pg_num_alpha.csv'
  # cora_mapper_path: "mappers/2023/cora_mapper.csv" ### DELETE
  itl1_detailed_mapper_path: "mappers/itl1_detailed.csv"
  ref_list_817_mapper_path: "mappers/2023/BERD_2022_ref_list.csv"
  civil_defence_detailed_mapper_path: "mappers/civil_defence_detailed.csv"
  sic_division_detailed_mapper_path: "mappers/sic_div_detailed.csv"

schema_paths:
  short_form_schema: "config/output_schemas/short_form_schema.toml"
  long_form_schema: "config/output_schemas/long_form_schema.toml"
  tau_schema: "config/output_schemas/tau_schema.toml"
  gb_sas_schema: "config/output_schemas/gb_sas_schema.toml"
  ni_sas_schema: "config/output_schemas/ni_sas_schema.toml"
  intram_by_pg_schema: "config/output_schemas/intram_by_pg_schema.toml"
  intram_by_itl1_schema: "config/output_schemas/intram_by_itl1_schema.toml"
  manual_trimming_schema: "config/output_schemas/manual_trimming_qa_schema.toml"
  cora_mapper_schema: "/config/cora_schema.toml"
  sic_pg_utf_schema : "/config/sic_pg_utf_schema.toml"
  status_filtered_schema: "config/output_schemas/status_filtered_schema.toml"
  fte_total_qa_schema: "config/output_schemas/fte_total_qa_schema.toml"
  intram_by_civil_defence_schema: "config/output_schemas/intram_by_civil_defence_schema.toml"
  intram_by_sic_schema: "config/output_schemas/intram_by_sic_schema.toml"
  frozen_group_schema: "config/output_schemas/frozen_group_schema.toml"
# Export config for users
outliers:
  flag_cols: ["701", "702", "703", "704", "705", "706", "707"] # NOT for user config. Columns to flag for outliers.
devtest:
  seltype_list: [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22, 23, 25, 26, 27, 29, 30, 31, 33, 34, 35, 37, 38, 39]
csv_filenames:
  main: "main_runlog.csv"
  configs: "configs_runlog.csv"
  logs: "logs_runlog.csv"
run_log_sql:
  log_db: "test_runlog"
  log_mode: "append"
estimation:
  numeric_cols: ["701", "702", "703", "704", "705", "706", "707", "709", "710", "711"]
imputation:
  lf_target_vars:
    - "211"
    - "305"
    - "emp_researcher"
    - "emp_technician"
    - "emp_other"
    - "headcount_res_m"
    - "headcount_res_f"
    - "headcount_tec_m"
    - "headcount_tec_f"
    - "headcount_oth_m"
    - "headcount_oth_f"
  sum_cols:
    - "emp_total"
    - "headcount_tot_m"
    - "headcount_tot_f"
    - "headcount_total"
breakdowns:
  "211":
    - "202"
    - "203"
    - "204"
    - "205"
    - "206"
    - "207"
    - "209"
    - "210"
    - "212"
    - "214"
    - "216"
    - "218"
    - "219"
    - "220"
    - "221"
    - "222"
    - "223"
    - "225"
    - "226"
    - "227"
    - "228"
    - "229"
    - "237"
    - "242"
    - "243"
    - "244"
    - "245"
    - "246"
    - "247"
    - "248"
    - "249"
    - "250"
  "305":
    - "302"
    - "303"
    - "304"
  emp_total:
    - "emp_researcher"
    - "emp_technician"
    - "emp_other"
  headcount_total:
    - "headcount_res_m"
    - "headcount_res_f"
    - "headcount_tec_m"
    - "headcount_tec_f"
    - "headcount_oth_m"
    - "headcount_oth_f"
