config_validation:
  validate: True
  path: src/dev_config_schema.yaml
global:
  # Logging settings
  log_to_file: True # Write logs to .log file
  logging_level: "DEBUG"
  table_config: "SingleLine"
  # Environment settings
  dev_test : False
  network_or_hdfs: "network" #whether to load from hdfs or network (local Python)
  # Construction Settings
  load_reference_list: True # the reference list corrections should always be loaded in year 1
  load_from_feather: True
  # Apportionment to sites settings
  apportion_sites: True
runlog_writer:
  write_csv: True # Write the runlog to a CSV file
  write_hdf5: False # Write the runlog to an HDF5 file
  write_sql: False # Write the runlog to a SQL database
  display: False # Display the runlog in the terminal
  log_path: "/ons/rdbe_dev/"
hdfs_paths:
  logs_foldername: "/ons/rdbe_dev/logs/run_logs"
staging_paths:
  folder: "01_staging"
  feather_output: "feather"
  staging_output_path: "staging_qa/full_responses_qa"
  pcode_val_path: "staging_qa/postcode_validation"
freezing_paths:
  folder: "02_freezing"
  frozen_data_staged_path: "frozen_data_staged"
  changes_to_review_path: "changes_to_review"
  freezing_updates_path: "freezing_updates"
ni_paths:
  folder: "03_northern_ireland"
  ni_staging_output_path: "ni_staging_qa"
construction_paths:
  folder: "04_construction"
  qa_path: "construction_qa"
mapping_paths:
  folder: "05_mapping"
  qa_path: "mapping_qa"
imputation_paths:
  folder: "06_imputation"
  qa_path: "imputation_qa"
  manual_trimming_path: "manual_trimming"
  backdata_out_path: "backdata_output"
outliers_paths:
  folder: "07_outliers"
  qa_path: "outliers_qa"
  auto_outliers_path: "auto_outliers"
estimation_paths:
  folder: "08_estimation"
  qa_path: "estimation_qa"
apportionment_paths:
  folder: "09_apportionment"
  qa_path: "apportionment_qa"
outputs_paths:
  folder: "10_outputs"
  #TODO: add all the output subpaths
  outputs_master: ""
pnp_paths:
  staging_qa_path: "01_staging/pnp_staging_qa"
export_paths:
  export_folder: "outgoing_export"
network_paths:
  root: "R:/BERD Results System Development 2023/DAP_emulation/"
  logs_foldername: "logs/run_logs" # dev config
  frozen_snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/spp_snapshots/2023_snapshots/snapshot-202312-002-b9b6048a-51c9-4669-919a-e92fc6e9c433.json" # dev config
  # snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/survey_return_data/snapshot-202212-002-83b5bacd-7c99-45cf-b989-d43d762dd054.json"
  secondary_snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/berd_survey/anonymised/v1/snapshot-202012-002-fba5c4ba-fb8c-4a62-87bb-66c725eea5fd.json" # TODO Check if this works
  ni_full_responses_path: "03_northern_ireland/2021/TEST_ni.csv" # TESTER FILE
  # Freezing data paths
  frozen_data_staged_path: None #"02_freezing/frozen_data_staged/"
  freezing_changes_to_review_path: None # "02_freezing/changes_to_review/"
  freezing_additions_path: None # "02_freezing/freezing_updates/"
  freezing_amendments_path: None # "02_freezing/freezing_updates/"
  # Imputation and outliers input paths
  # backdata_path: "R:/BERD Results System Development 2023/2021_data/2021_backdata_expanded.csv"
  backdata_path: "R:/BERD Results System Development 2023/DAP_emulation/2022_surveys/BERD/06_imputation/backdata_output/2022_backdata_published_v347.csv"
  manual_imp_trim_path: "06_imputation/manual_trimming/trimming_qa_2023-11-27_v359.csv"
  manual_outliers_path: "07_outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  # Construction paths
  all_data_construction_file_path: "04_construction/manual_construction/2023_test_construction_file.csv"
  postcode_construction_file_path: "04_construction/manual_construction/2023_test_postcode_construction_file.csv"
  construction_file_path_ni: "04_construction/manual_construction/test_construction_ni_file.csv"
  # postcode paths
  postcode_masterlist: "R:/BERD Results System Development 2023/DAP_emulation/ONS_Postcode_Reference/postcodes_pcd2_itl.csv"
  pcode_val_path: "01_staging/staging_qa/postcode_validation"
# schema paths
schema_paths:
  manual_trimming_schema: "config/output_schemas/manual_trimming_qa_schema.toml"
  short_form_schema: "config/output_schemas/short_form_schema.toml"
  long_form_schema: "config/output_schemas/long_form_schema.toml"
  tau_schema: "config/output_schemas/tau_schema.toml"
  gb_sas_schema: "config/output_schemas/gb_sas_schema.toml"
  ni_sas_schema: "config/output_schemas/ni_sas_schema.toml"
  intram_by_pg_gb_schema: "config/output_schemas/intram_by_pg_gb_schema.toml"
  intram_by_pg_uk_schema: "config/output_schemas/intram_by_pg_uk_schema.toml"
  intram_gb_itl1_schema: "config/output_schemas/intram_gb_itl1_schema.toml"
  intram_gb_itl2_schema: "config/output_schemas/intram_gb_itl2_schema.toml"
  intram_uk_itl1_schema: "config/output_schemas/intram_uk_itl1_schema.toml"
  intram_uk_itl2_schema: "config/output_schemas/intram_uk_itl2_schema.toml"
  intram_by_sic_schema: "config/output_schemas/intram_by_sic_schema.toml"
  status_filtered_qa_schema: "config/output_schemas/status_filtered_qa_schema.toml"
  fte_total_qa_schema: "config/output_schemas/fte_total_qa_schema.toml"
  frozen_group_schema: "config/output_schemas/frozen_group_schema.toml"
  full_estimation_qa_schema: "config/output_schemas/full_estimation_qa_schema.toml"
  full_responses_imputed_schema: "config/output_schemas/full_responses_imputed_schema.toml"
  staged_BERD_full_responses_schema: "config/output_schemas/staged_BERD_full_responses_schema.toml"
  invalid_unrecognised_postcodes_schema: "config/output_schemas/invalid_unrecognised_postcodes_schema.toml"
# Export config for users
outliers:
  flag_cols: ["701", "702", "703", "704", "705", "706", "707"] # NOT for user config. Columns to flag for outliers.
devtest:
  seltype_list: [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22, 23, 25, 26, 27, 29, 30, 31, 33, 34, 35, 37, 38, 39]
log_filenames:
  main: "main_runlog.csv"
  configs: "configs_runlog.csv"
  logs: "logs_runlog.csv"
run_log_sql:
  log_db: "test_runlog"
  log_mode: "append"
estimation:
  numeric_cols: ["701", "702", "703", "704", "705", "706", "707", "709", "710", "711"]
imputation:
  lf_target_vars:
    - "211"
    - "305"
    - "emp_researcher"
    - "emp_technician"
    - "emp_other"
    - "headcount_res_m"
    - "headcount_res_f"
    - "headcount_tec_m"
    - "headcount_tec_f"
    - "headcount_oth_m"
    - "headcount_oth_f"
  sum_cols:
    - "emp_total"
    - "headcount_tot_m"
    - "headcount_tot_f"
    - "headcount_total"
breakdowns:
  "211":
    - "202"
    - "203"
    - "204"
    - "205"
    - "206"
    - "207"
    - "209"
    - "210"
    - "212"
    - "214"
    - "216"
    - "218"
    - "219"
    - "220"
    - "221"
    - "222"
    - "223"
    - "225"
    - "226"
    - "227"
    - "228"
    - "229"
    - "237"
    - "242"
    - "243"
    - "244"
    - "245"
    - "246"
    - "247"
    - "248"
    - "249"
    - "250"
  "305":
    - "302"
    - "303"
    - "304"
  emp_total:
    - "emp_researcher"
    - "emp_technician"
    - "emp_other"
  headcount_total:
    - "headcount_res_m"
    - "headcount_res_f"
    - "headcount_tec_m"
    - "headcount_tec_f"
    - "headcount_oth_m"
    - "headcount_oth_f"
