global:
  log_to_file: True # Write logs to .log file
  logging_level: "DEBUG"
  table_config: "SingleLine"
  postcode_csv_check: False
  network_or_hdfs: network #whether to load from hdfs or network (local Python)
years:
  current_year: 2022 # TODO: put this in the userconfig
  previous_years_to_load: 1 # TODO: put this in the userconfig
runlog_writer:
    write_csv: True # Write the runlog to a CSV file
    write_hdf5: False # Write the runlog to an HDF5 file
    write_sql: False # Write the runlog to a SQL database
    display: False # Display the runlog in the terminal
    log_path: "data/log"
hdfs_paths:
  root: None
  logs_foldername: "resdev/logs/run_logs"
  snapshot_path: "/ons/rdbe_dev/berd_survey/anonymised/v1/snapshot-202012-002-fba5c4ba-fb8c-4a62-87bb-66c725eea5fd.json"
  postcode_masterlist: "data/external/ONSPD_NOV_2022_UK.csv"
  history_path: "/ons/rdbe_dev/backseries/anonymised/v1"
network_paths:
  root: None
  logs_foldername: "logs/run_logs"
  snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/berd_survey/spp_snapshots/v1/snapshot-202212-002-83b5bacd-7c99-45cf-b989-d43d762dd054.json"
  postcode_masterlist: "R:/BERD Results System Development 2023/DAP_emulation/ONS_Postcode_Reference/ONSPD_NOV_2022_UK.csv"
  history_path: "R:/BERD Results System Development 2023/DAP_emulation/backseries/anonymised/v1"
  staging_path: "R:/BERD Results System Development 2023/DAP_emulation/staging"
  imputation_path: "R:/BERD Results System Development 2023/DAP_emulation/imputation" 
  estimation_path: "R:/BERD Results System Development 2023/DAP_emulation/estimation" 
  outputs_path: "R:/BERD Results System Development 2023/DAP_emulation/outputs" 

csv_filenames:
    main: "main_runlog.csv"
    configs: "configs_runlog.csv"
    logs: "logs_runlog.csv"
run_log_sql:
    log_db: "test_runlog"
    log_mode: "append"
