global:
  # Logging settings
  log_to_file: True # Write logs to .log file
  logging_level: "DEBUG"
  table_config: "SingleLine"
  # Environment settings
  dev_test : False
  network_or_hdfs: network #whether to load from hdfs or network (local Python)
  # Staging and validation settings
  postcode_csv_check: False
  load_updated_snapshot: False # Whether to load the updated snapshots for amendments and additions
  load_ni_data: False
  load_historic_data: False
  run_construction: False
  run_ni_construction: False
  load_manual_outliers: False
  load_manual_imputation: False
  load_backdata: True  # whether to load previous year data for MoR
  load_reference_list: True # the reference list corrections should always be loaded in year 1
  load_from_feather: True
  # Apportionment to sites settings
  apportion_sites: True
  # Output settings
  output_full_responses: False
  output_ni_full_responses: False
  output_auto_outliers: False
  output_outlier_qa : False
  output_estimation_qa: False
  output_apportionment_qa: False
  output_long_form: False
  output_short_form: False
  output_gb_sas: False
  output_ni_sas: False
  output_tau: False
  output_intram_by_pg: False
  output_intram_by_itl1: False
  output_intram_by_civil_defence: False
  output_intram_by_sic: False
  output_status_filtered: True
  output_fte_total_qa: False
years:
  current_year: 2022 # TODO: put this in the userconfig
  previous_years_to_load: 1 # TODO: put this in the userconfig
runlog_writer:
    write_csv: True # Write the runlog to a CSV file
    write_hdf5: False # Write the runlog to an HDF5 file
    write_sql: False # Write the runlog to a SQL database
    display: False # Display the runlog in the terminal
    log_path: "/ons/rdbe_dev/"
hdfs_paths:
  root: "/ons/rdbe_dev/"
  logs_foldername: "/ons/rdbe_dev/logs/run_logs"
  snapshot_path: "/ons/rdbe_dev/berd_survey/anonymised/v1/snapshot-202012-002-fba5c4ba-fb8c-4a62-87bb-66c725eea5fd.json"
  secondary_snapshot_path: "/ons/rdbe_dev/berd_survey/anonymised/v1/NEW_SNAPSHOT_TODO.json"
  postcode_masterlist: "/ons/rdbe_dev/mappers/2023/ONSPD_NOV_2022_UK.csv"
  postcode_path: "/ons/rdbe_dev/staging/staging_qa/postcode_validation"
  ultfoc_mapper_path: "/ons/rdbe_dev/mappers/2023/BERD_2022_ultfoc_anon.csv"

  staging_output_path: "/ons/rdbe_dev/staging/staging_qa/full_responses_qa"
  output_path:  "/ons/rdbe_dev/outputs"
  cellno_2022_path: "/ons/rdbe_dev/mappers/2023/berd_2022_cellno_coverage.csv"
  itl_mapper_path: "/ons/rdbe_dev/mappers/2023/itl.csv"
  history_path: "/ons/rdbe_dev/BERD_V7_Anonymised"
  backdata_path: ""
  manual_outliers_path: "/ons/rdbe_dev/outliers/manual_outliers/manual_outlier_2023_09_09_sample_amonymised.csv"
  imputation_path: "/ons/rdbe_dev/imputation"
  manual_imp_trim_path: "/ons/rdbe_dev/imputation/manual_trimming"
  outliers_path: "/ons/rdbe_dev/outliers"
  estimation_path:  "/ons/rdbe_dev/estimation"
  short_form_schema: "src/outputs/output_schemas/short_form_schema.toml"
  long_form_schema: "src/outputs/output_schemas/long_form_schema.toml"
  export_path: /ons/rdbe_dev/outgoing_export
  feather_path: "/ons/rdbe_dev/staging/feather"
network_paths:
  root: "R:/BERD Results System Development 2023/DAP_emulation/"
  logs_foldername: "logs/run_logs"
  snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/survey_return_data/snapshot-202212-002-83b5bacd-7c99-45cf-b989-d43d762dd054.json"
  secondary_snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/berd_survey/anonymised/v1/snapshot-202012-002-fba5c4ba-fb8c-4a62-87bb-66c725eea5fd.json" # TODO Check if this works
  ni_full_responses_path: "R:/BERD Results System Development 2023/DAP_emulation/northern_ireland/2021/TEST_ni.csv" # TESTER FILE
  postcode_masterlist: "R:/BERD Results System Development 2023/DAP_emulation/ONS_Postcode_Reference/postcodes_pcd2_itl.csv"
  postcode_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/staging_qa/postcode_validation"
  staging_test_foldername: "R:/BERD Results System Development 2023/Staged_Test_Output"
  staging_output_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/staging_qa/full_responses_qa"
  ni_staging_output_path: "R:/BERD Results System Development 2023/DAP_emulation/northern_ireland/ni_staging_qa"
  history_path: "R:/BERD Results System Development 2023/DAP_emulation/BERD_V7_Anonymised" #"R:\BERD Results System Development 2023\DAP_emulation\backseries\v1"
  backdata_path: "R:/BERD Results System Development 2023/2021_data/validation-extract-responses-202112.csv"
  outliers_path: "R:/BERD Results System Development 2023/DAP_emulation/outliers"
  manual_outliers_path: "R:/BERD Results System Development 2023/DAP_emulation/outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  construction_file_path: "R:/BERD Results System Development 2023/DAP_emulation/construction/manual_construction/JC_test_construction_file.csv"
  construction_file_path_ni: "R:/BERD Results System Development 2023/DAP_emulation/construction/manual_construction/test_construction_ni_file.csv"
  # construction_add_path: "R:/BERD Results System Development 2023/DAP_emulation/construction/manual_construction/construction_additions_2023-11-06_v5.csv" # TODO Need to test
  # construction_amend_path:  "R:/BERD Results System Development 2023/DAP_emulation/construction/manual_construction/construction_amendments_2023-10-31_v2.csv" # TODO Need to test
  estimation_path:  "R:/BERD Results System Development 2023/DAP_emulation/estimation"
  imputation_path:  "R:/BERD Results System Development 2023/DAP_emulation/imputation"
  manual_imp_trim_path: "R:/BERD Results System Development 2023/DAP_emulation/imputation/manual_trimming/trimming_qa_2023-11-27_v359.csv"
  construction_path: "R:/BERD Results System Development 2023/DAP_emulation/construction"
  apportionment_path:  "R:/BERD Results System Development 2023/DAP_emulation/apportionment"
  output_path:  "R:/BERD Results System Development 2023/DAP_emulation/outputs"
  cellno_2022_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/berd_2022_cellno_coverage.csv'
  export_path: "R:/BERD Results System Development 2023/DAP_emulation/outgoing_export"
  itl_mapper_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/itl.csv'
  feather_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/feather"
  mapper_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers'
  sic_pg_utf_mapper_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/SIC_to_PG_UTF-8.csv'
  cora_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/cora_mapper.csv" #input for mapping status to cora "form_stauts"
  ultfoc_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/BERD_2022_ultfoc.csv"
  pg_num_alpha_mapper_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/pg_num_alpha.csv'
  sic_pg_alpha_mapper_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/sic_pg_alpha.csv'
  pg_detailed_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/pg_detailed.csv"
  itl1_detailed_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/itl1_detailed.csv"
  ref_list_817_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/BERD_2022_ref_list.csv"
  civil_defence_detailed_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/civil_defence_detailed.csv"
  sic_division_detailed_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/sic_div_detailed.csv"
schema_paths:
  short_form_schema: "config/output_schemas/short_form_schema.toml"
  long_form_schema: "config/output_schemas/long_form_schema.toml"
  tau_schema: "config/output_schemas/tau_schema.toml"
  gb_sas_schema: "config/output_schemas/gb_sas_schema.toml"
  ni_sas_schema: "config/output_schemas/ni_sas_schema.toml"
  intram_by_pg_schema: "config/output_schemas/intram_by_pg_schema.toml"
  intram_by_itl1_schema: "config/output_schemas/intram_by_itl1_schema.toml"
  manual_trimming_schema: "config/output_schemas/manual_trimming_qa_schema.toml"
  cora_mapper_schema: "/config/cora_schema.toml"
  sic_pg_utf_schema : "/config/sic_pg_utf_schema.toml"
  status_filtered_schema: "config/output_schemas/status_filtered_schema.toml"
  fte_total_qa_schema: "config/output_schemas/fte_total_qa_schema.toml"
  intram_by_civil_defence_schema: "config/output_schemas/intram_by_civil_defence_schema.toml"
  intram_by_sic_schema: "config/output_schemas/intram_by_sic_schema.toml"


# Export config for users



# / ons/ rdbe_dev/ outputs/ output_short_form/ output_short_form2023-09-12_v1.csv

outliers:
    upper_clip: 0.05  # enter percentage as a decimal (float) - default is 0.05
    lower_clip: 0.0  # enter percentage as a decimal (float) - default is 0.0
    flag_cols: ["701", "702", "703", "704", "705", "706", "707"] # NOT for user config. Columns to flag for outliers.
devtest:
    seltype_list: [1, 2, 3, 5, 6, 7, 9, 10, 11, 13, 14, 15, 17, 18, 19, 21, 22, 23, 25, 26, 27, 29, 30, 31, 33, 34, 35, 37, 38, 39]
csv_filenames:
    main: "main_runlog.csv"
    configs: "configs_runlog.csv"
    logs: "logs_runlog.csv"
run_log_sql:
    log_db: "test_runlog"
    log_mode: "append"
estimation:
  numeric_cols: ["701", "702", "703", "704", "705", "706", "707", "709", "710", "711"]
imputation:
  lower_trim_perc: 15
  upper_trim_perc: 15
  trim_threshold: 10 # trimming will only occur on classes strictly larger than this value
  sf_expansion_threshold: 3 # default is 3: the minimum viable imputation class size for short form imputation
  lf_target_vars:
    - "211"
    - "305"
    - "emp_researcher"
    - "emp_technician"
    - "emp_other"
    - "headcount_res_m"
    - "headcount_res_f"
    - "headcount_tec_m"
    - "headcount_tec_f"
    - "headcount_oth_m"
    - "headcount_oth_f"
  sum_cols:
    - "emp_total"
    - "headcount_tot_m"
    - "headcount_tot_f"
    - "headcount_total"
breakdowns:
  "211":
    - "202"
    - "203"
    - "204"
    - "205"
    - "206"
    - "207"
    - "209"
    - "210"
    - "212"
    - "214"
    - "216"
    - "218"
    - "219"
    - "220"
    - "221"
    - "222"
    - "223"
    - "225"
    - "226"
    - "227"
    - "228"
    - "229"
    - "237"
    - "242"
    - "243"
    - "244"
    - "245"
    - "246"
    - "247"
    - "248"
    - "249"
    - "250"
  "305":
    - "302"
    - "303"
    - "304"
  emp_total:
    - "emp_researcher"
    - "emp_technician"
    - "emp_other"
  headcount_total:
    - "headcount_res_m"
    - "headcount_res_f"
    - "headcount_tec_m"
    - "headcount_tec_f"
    - "headcount_oth_m"
    - "headcount_oth_f"
