global:
  log_to_file: True # Write logs to .log file
  logging_level: "DEBUG"
  table_config: "SingleLine"
  postcode_csv_check: True
  load_historic_data: False
  load_manual_outliers: False
  output_full_responses: False
  output_auto_outliers: False
  output_outlier_qa : False
  output_estimation_qa: False
  output_imputation_qa: True
  output_short_form: True
  dev_test : False
  network_or_hdfs: network #whether to load from hdfs or network (local Python)
  load_from_feather: True
years:
  current_year: 2022 # TODO: put this in the userconfig
  previous_years_to_load: 1 # TODO: put this in the userconfig
runlog_writer:
    write_csv: True # Write the runlog to a CSV file
    write_hdf5: False # Write the runlog to an HDF5 file
    write_sql: False # Write the runlog to a SQL database
    display: False # Display the runlog in the terminal
    log_path: "data/log"
hdfs_paths:
  root: None
  logs_foldername: "/ons/rdbe_dev/logs/run_logs"
  snapshot_path: "/ons/rdbe_dev/snapshot-202012-002-fba5c4ba-fb8c-4a62-87bb-66c725eea5fd.json"
  postcode_masterlist: "/ons/rdbe_dev/mappers/2023/ONSPD_NOV_2022_UK.csv"
  postcode_path: "/ons/rdbe_dev/staging/staging_qa/postcode_validation"
  pg_mapper_path: "/ons/rdbe_dev/mappers/2023/SIC_to_PG_UTF-8.csv"
  ultfoc_mapper_path: "/ons/rdbe_dev/mappers/2023/BERD_2022_ultfoc_anon.csv"
  cora_mapper_path: "/ons/rdbe_dev/mappers/2023/cora_mapper.csv"
  staging_output_path: "/ons/rdbe_dev/staging/staging_qa/full_responses_qa"
  output_path:  "/ons/rdbe_dev/outputs"
  cellno_path: "/ons/rdbe_dev/mappers/2023/berd_2022_cellno_coverage.csv"
  itl_path: "/ons/rdbe_dev/mappers/2023/itl.csv"
  history_path: "/ons/rdbe_dev/BERD_V7_Anonymised"
  outliers_path: None
  feather_path: "/ons/rdbe_dev/staging/feather"
network_paths:
  root: None
  logs_foldername: "logs/run_logs"
  snapshot_path: "R:/BERD Results System Development 2023/DAP_emulation/survey_return_data/snapshot-202212-002-83b5bacd-7c99-45cf-b989-d43d762dd054.json"
  postcode_masterlist: "R:/BERD Results System Development 2023/DAP_emulation/ONS_Postcode_Reference/postcodes_pcd2_itl.csv"
  postcode_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/staging_qa/postcode_validation"
  pg_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/SIC_to_PG.csv"
  cora_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/cora_mapper.csv" #input for mapping status to cora "form_stauts"
  ultfoc_mapper_path: "R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/BERD_2022_ultfoc.csv"
  staging_test_foldername: "R:/BERD Results System Development 2023/Staged_Test_Output"
  staging_output_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/staging_qa/full_responses_qa"
  history_path: "R:/BERD Results System Development 2023/DAP_emulation/BERD_V7_Anonymised" #"R:\BERD Results System Development 2023\DAP_emulation\backseries\v1"
  outliers_path: "R:/BERD Results System Development 2023/DAP_emulation/outliers"
  manual_outliers_path: "R:/BERD Results System Development 2023/DAP_emulation/outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  estimation_path:  "R:/BERD Results System Development 2023/DAP_emulation/estimation"
  imputation_path:  "R:/BERD Results System Development 2023/DAP_emulation/imputation"
  output_path:  "R:/BERD Results System Development 2023/DAP_emulation/outputs"
  cellno_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/berd_2022_cellno_coverage.csv'
  itl_path: 'R:/BERD Results System Development 2023/DAP_emulation/mappers/2023/itl.csv'
  feather_path: "R:/BERD Results System Development 2023/DAP_emulation/staging/feather"
schema_paths:
  frozen_shortform_schema: "src/outputs/output_schemas/frozen_shortform_schema.toml"
outliers:
    upper_clip: 0.05  # enter percentage as a decimal (float) - default is 0.05
    lower_clip: 0.0  # enter percentage as a decimal (float) - default is 0.0
    flag_cols: ["701", "702", "703", "704", "705", "706", "707"] # NOT for user config. Columns to flag for outliers.
csv_filenames:
    main: "main_runlog.csv"
    configs: "configs_runlog.csv"
    logs: "logs_runlog.csv"
run_log_sql:
    log_db: "test_runlog"
    log_mode: "append"
breakdowns:
  2xx:
    - "202"
    - "203"
    - "204"
    - "205"
    - "206"
    - "207"
    - "209"
    - "210"
    - "212"
    - "214"
    - "216"
    - "218"
    - "219"
    - "220"
    - "221"
    - "222"
    - "223"
    - "225"
    - "226"
    - "227"
    - "228"
    - "229"
    - "237"
    - "242"
    - "243"
    - "244"
    - "245"
    - "246"
    - "247"
    - "248"
    - "249"
    - "250"
  3xx:
    - "302"
    - "303"
    - "304"
