config_validation:
  validate: True
  path: src/user_config_schema.yaml
years:
  survey_year: 2023
global:
  # Staging and validation settings
  postcode_csv_check: True
  load_updated_snapshot: False # Whether to load the updated snapshots for amendments and additions
  load_ni_data: False
  # Construction Settings
  run_all_data_construction: False
  run_postcode_construction: False
  run_ni_construction: False
  load_manual_outliers: False
  load_manual_imputation: False
  load_backdata: True  # whether to load previous year data for MoR
  # Backdata output settings
  output_backdata: False
  # QA output settings
  output_full_responses: False
  output_pnp_full_responses: False
  output_ni_full_responses: False
  output_imputation_qa: False
  output_mapping_qa: True
  output_mapping_ni_qa: False
  output_auto_outliers: False
  output_outlier_qa : False
  output_estimation_qa: False
  output_apportionment_qa: False
  # Final output settings
  output_long_form: True
  output_short_form: True
  output_gb_sas: True
  output_ni_sas: False
  output_tau: True
  output_intram_by_pg_gb: True
  output_intram_by_pg_uk: True
  output_intram_gb_itl: True
  output_intram_uk_itl: True
  output_intram_by_civil_defence: True
  output_intram_by_sic: True
  output_fte_total_qa: True
  output_status_filtered: False
  output_frozen_group: True
hdfs_paths:
  root: "/ons/rdbe_dev/"
  # staging input paths
  snapshot_path: "/ons/rdbe_dev/spp_snapshots/2023_snapshots/snapshot-202312-002-b9b6048a-51c9-4669-919a-e92fc6e9c433.json"
  secondary_snapshot_path: "/ons/rdbe_dev/berd_survey/anonymised/v1/NEW_SNAPSHOT_TODO.json"
  ni_full_responses_path: "03_northern_ireland/2021/TEST_ni.csv"
  feather_path: "staging/feather"
  # Imputation and outliers input paths
  backdata_path: ""
  manual_imp_trim_path: "06_imputation/manual_trimming/trimming_qa_2023-11-27_v359.csv"
  manual_outliers_path: "07_outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  # Construction paths
  all_data_construction_file_path:  "04_construction/manual_construction/test_construction_file.csv"
  postcode_construction_file_path: "04_construction/manual_construction/test_postcode_construction_file.csv"
  construction_file_path_ni:  "04_construction/manual_construction/test_construction_file.csv"
  # postcode paths
  postcode_masterlist: "/ons/rdbe_dev/mappers/2023/ONSPD_NOV_2022_UK.csv"
  pcode_val_path: "01_staging/staging_qa/postcode_validation"
  # mapper paths
2022_mappers:
  mappers_version: "v1"
  postcode_mapper: "postcodes_2022.csv"
  itl_mapper_path: "itl_2022.csv"
  ultfoc_mapper_path: "BERD_2022_ultfoc.csv"
  ref_list_817_mapper_path: "BERD_2022_ref_list.csv"
  cellno_path: 'berd_2022_cellno_coverage.csv'
  pg_num_alpha_mapper_path: 'pg_num_alpha_2022.csv'
  sic_pg_alpha_mapper_path: 'sic_pg_alpha_2022.csv'
  sic_pg_num_mapper_path: 'sic_pg_num_2022.csv'
  pg_detailed_mapper_path: "pg_detailed_2022.csv"
  itl1_detailed_mapper_path: "itl1_detailed_2022.csv"
  civil_defence_detailed_mapper_path: "civil_defence_detailed_2022.csv"
  sic_division_detailed_mapper_path: "sic_div_detailed_2022.csv"
2023_mappers:
  mappers_version: "v1"
  postcode_mapper: "postcodes_2023.csv"
  itl_mapper_path: "itl_2023.csv"
  ultfoc_mapper_path: "BERD_2023_ultfoc_anon.csv"
  cellno_path: 'BERD_2023_cellno_coverage.csv'
  pg_num_alpha_mapper_path: 'pg_num_alpha_2023.csv'
  sic_pg_alpha_mapper_path: 'sic_pg_alpha_2023.csv'
  sic_pg_num_mapper_path: 'sic_pg_num_2023.csv'
  pg_detailed_mapper_path: "pg_detailed_2023.csv"
  itl1_detailed_mapper_path: "itl1_detailed_2023.csv"
  civil_defence_detailed_mapper_path: "civil_defence_detailed_2023.csv"
  sic_division_detailed_mapper_path: "sic_div_detailed_2023.csv"
# outliers and imputation settings
outliers:
  upper_clip: 0.05  # enter percentage as a decimal (float) - default is 0.05
  lower_clip: 0.0  # enter percentage as a decimal (float) - default is 0.0
imputation:
  lower_trim_perc: 15
  upper_trim_perc: 15
  trim_threshold: 10 # trimming will only occur on classes strictly larger than this value
  sf_expansion_threshold: 3 # default is 3: the minimum viable imputation class size for short form imputation
  mor_threshold: 3 # default is 3: the minimum viable imputation class size for MoR imputation
# export settings
export_choices:
  copy_or_move_files: "copy"
  export_short_form: None
  export_long_form: None
  export_tau: None
  export_gb_sas: None
  export_ni_sas: None
  export_intram_by_pg_gb: None
  export_intram_by_pg_uk: None
  export_intram_gb_itl1: None
  export_intram_uk_itl1: None
  export_intram_gb_itl2: None
  export_intram_uk_itl2: None
  export_intram_by_sic: None
  export_fte_total_qa: None
  export_status_filtered: None
  export_frozen_group: None
  export_staged_BERD_full_responses: None
  export_staged_NI_full_responses: None
  export_full_responses_imputed: None
  export_full_estimation_qa: None  # "2022_full_estimation_qa_24-07-15_v555.csv"
  export_invalid_unrecognised_postcodes: "2022_invalid_unrecognised_postcodes_24-07-04_v503.csv"
