# top_level: bool: is this top level where dt is the same?
# bottom_level: bool: is this bottom level e.g., singular dtype for one item
# dtype: [str, int, float, bool, path]
# accept_nonetype: bool: whether or not to accept None
# max: [int, float]: applies only to int/float dtype, optional (inclusive)
# min: [int, float]: applies only to int/float dtype, optional (inclusive)
# filetype: str: applies to only path dtype, optional (using '.' optional)
global:
  top_level: True
  bottom_level: False
  dtype: "bool"
  accept_nonetype: False
  max: null
  min: null
  filetype: null
years:
  current_year:
    top_level: False
    bottom_level: True
    dtype: "int"
    accept_nonetype: False
    max: null
    min: 2022
  previous_years_to_load:
    top_level: False
    bottom_level: True
    dtype: "int"
    accept_nonetype: False
    max: null
    min: 0
hdfs_paths:
  top_level: True
  bottom_level: False
  dtype: "path"
  accept_nonetype: True
network_paths:
  top_level: True
  bottom_level: False
  dtype: "path"
  accept_nonetype: True
# Export config for users
outliers:
  top_level: True
  bottom_level: False
  dtype: "float"
  accept_nonetype: False
  min: 0
imputation:
  top_level: True
  bottom_level: False
  dtype: "int"
  accept_nonetype: False
  min: 0
  