config_validation:
  validate: True
  path: src/user_config_schema.yaml
years:
  survey_year: 2023
global:
  # Staging and validation settings
  postcode_csv_check: True
  load_ni_data: True
  # Pipeline run type
  run_with_snapshot: True                         # Run until point of freezing
  run_with_snapshot_and_freeze: False             # Last run with frozen snapshot - produces frozen csv
  run_with_frozen_data: False                     # Run with specified frozen csv
  # Freezing settings
  load_updated_snapshot_for_comparison: False     # Run with new json snapshot, and compare to specified frozen csv
  run_updates_and_freeze: False                   # Add specified changes to frozen csv, and refreeze
  # Construction Settings
  run_all_data_construction: False
  run_postcode_construction: False
  run_ni_construction: False
  load_manual_outliers: False
  load_manual_imputation: False
  # Backdata output settings
  output_backdata: False
  # QA output settings
  output_full_responses: False
  output_pnp_full_responses: False
  output_ni_full_responses: False
  output_mapping_qa: False
  output_mapping_ni_qa: False
  output_imputation_qa: False
  output_auto_outliers: False
  output_outlier_qa : False
  output_estimation_qa: False
  output_apportionment_qa: False
  # Final output settings
  output_long_form: False
  output_short_form: False
  output_gb_sas: False
  output_ni_sas: False
  output_tau: False
  output_intram_by_pg_gb: False
  output_intram_by_pg_uk: False
  output_intram_gb_itl: False
  output_intram_uk_itl: False
  output_intram_by_civil_defence: False
  output_intram_by_sic: False
  output_fte_total_qa: False
  output_status_filtered: False
  output_frozen_group: False
  output_intram_totals: False
hdfs_paths:
  root: "/ons/rdbe_dev/"
  # staging input paths
  snapshot_path: "/ons/rdbe_dev/spp_snapshots/2023_snapshots/snapshot-202312-002-85ae5659-7147-42c3-a5dd-d69beccc9e09.json" #  Run until point of freezing - last run is first freeze
  updated_snapshot_path: "s3a://onscdp-dev-data01-5320d6ca/bat/res_dev/anonymised/snapshot_202312_a_copy_of_202012_anon.json" 
  ni_full_responses_path: "03_northern_ireland/2021/TEST_ni.csv"
  feather_path: "staging/feather"
  # Freezing data paths
  frozen_data_staged_output_path: "02_freezing/frozen_data_staged" # path for folder
  frozen_data_staged_path: "02_freezing/frozen_data_staged/2023_FROZEN_staged_BERD_full_responses_24-08-07_v906" # pragma: allowlist secret
  freezing_changes_to_review_path: "02_freezing/changes_to_review"
  freezing_additions_path: "02_freezing/freezing_updates"
  freezing_amendments_path: "02_freezing/freezing_updates"
  # Imputation and outliers input paths
  backdata_path: ""
  manual_imp_trim_path: "06_imputation/manual_trimming/trimming_qa_2023-11-27_v359.csv"
  manual_outliers_path: "07_outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  # Construction paths
  all_data_construction_file_path:  "04_construction/manual_construction/test_construction_file - Copy.csv"
  postcode_construction_file_path: "04_construction/manual_construction/test_postcode_construction_file.csv"
  construction_file_path_ni:  "04_construction/manual_construction/test_construction_file.csv"
  # postcode paths
  postcode_masterlist: "/ons/rdbe_dev/mappers/2023/ONSPD_NOV_2022_UK.csv"
  pcode_val_path: "01_staging/staging_qa/postcode_validation"
  # mapper paths
s3_paths:
  root: "/ons/rdbe_dev/"
  # staging input paths
  snapshot_path: "s3a://onscdp-dev-data01-5320d6ca/bat/res_dev/anonymised/snapshot_202312_a_copy_of_202012_anon.json"  #  Run until point of freezing - last run is first freeze
  updated_snapshot_path: "s3a://onscdp-dev-data01-5320d6ca/bat/res_dev/anonymised/snapshot_202312_a_copy_of_202012_anon.json" 
  ni_full_responses_path: "03_northern_ireland/2021/TEST_ni.csv"
  feather_path: "staging/feather"
  # Freezing data paths
  frozen_data_staged_path: "02_freezing/frozen_data_staged"
  freezing_changes_to_review_path: "02_freezing/changes_to_review"
  freezing_additions_path: "02_freezing/freezing_updates"
  freezing_amendments_path: "02_freezing/freezing_updates"
  # Imputation and outliers input paths
  backdata_path: ""
  manual_imp_trim_path: "06_imputation/manual_trimming/trimming_qa_2023-11-27_v359.csv"
  manual_outliers_path: "07_outliers/manual_outliers/manual_outlier_2023-08-29_v67.csv"
  # Construction paths
  all_data_construction_file_path:  "04_construction/manual_construction/test_construction_file.csv"
  postcode_construction_file_path: "04_construction/manual_construction/test_postcode_construction_file.csv"
  construction_file_path_ni:  "04_construction/manual_construction/test_construction_file.csv"
  # postcode paths
  postcode_masterlist: "/ons/rdbe_dev/mappers/2023/ONSPD_NOV_2022_UK.csv"
  pcode_val_path: "01_staging/staging_qa/postcode_validation"
  # mapper paths
2022_mappers:
  mappers_version: "v1"
  postcode_mapper: "postcodes_2022.csv"
  itl_mapper_path: "itl_2022.csv"
  ultfoc_mapper_path: "BERD_2022_ultfoc.csv"
  ref_list_817_mapper_path: "BERD_2022_ref_list.csv"
  cellno_path: 'berd_2022_cellno_coverage.csv'
  pg_num_alpha_mapper_path: 'pg_num_alpha_2022.csv'
  sic_pg_alpha_mapper_path: 'sic_pg_alpha_2022.csv'
  sic_pg_num_mapper_path: 'sic_pg_num_2022.csv'
  pg_detailed_mapper_path: "pg_detailed_2022.csv"
  civil_defence_detailed_mapper_path: "civil_defence_detailed_2022.csv"
  sic_division_detailed_mapper_path: "sic_div_detailed_2022.csv"
2023_mappers:
  mappers_version: "v2"
  postcode_mapper: "postcodes_2023.csv"
  itl_mapper_path: "itl_2023.csv"
  ultfoc_mapper_path: "BERD_2023_ultfoc.csv"
  cellno_path: 'BERD_2023_cellno_coverage.csv'
  pg_num_alpha_mapper_path: 'pg_num_alpha_2023.csv'
  sic_pg_alpha_mapper_path: 'sic_pg_alpha_2023.csv'
  sic_pg_num_mapper_path: 'sic_pg_num_2023.csv'
  pg_detailed_mapper_path: "pg_detailed_2023.csv"
  civil_defence_detailed_mapper_path: "civil_defence_detailed_2023.csv"
  sic_division_detailed_mapper_path: "sic_div_detailed_2023.csv"
# outliers and imputation settings
outliers:
  upper_clip: 0.05  # enter percentage as a decimal (float) - default is 0.05
  lower_clip: 0.0  # enter percentage as a decimal (float) - default is 0.0
imputation:
  lower_trim_perc: 15
  upper_trim_perc: 15
  trim_threshold: 10 # trimming will only occur on classes strictly larger than this value
  sf_expansion_threshold: 3 # default is 3: the minimum viable imputation class size for short form imputation
  mor_threshold: 3 # default is 3: the minimum viable imputation class size for MoR imputation
# export settings
export_choices:
  copy_or_move_files: "copy"
  export_short_form: None
  export_long_form: None
  export_tau: None
  export_gb_sas: None
  export_ni_sas: None
  export_intram_by_pg_gb: None
  export_intram_by_pg_uk: None
  export_intram_gb_itl1: None
  export_intram_uk_itl1: None
  export_intram_gb_itl2: None
  export_intram_uk_itl2: None
  export_intram_by_sic: None
  export_fte_total_qa: None
  export_status_filtered: None
  export_frozen_group: None
  export_staged_BERD_full_responses: None
  export_staged_NI_full_responses: None
  export_full_responses_imputed: None
  export_full_estimation_qa: None  # "2022_full_estimation_qa_24-07-15_v555.csv"
  export_invalid_unrecognised_postcodes: "2022_invalid_unrecognised_postcodes_24-07-04_v503.csv"
