name: Run mypy on pull request to develop

# runs on every pull request to develop
on:
  # pull_request:
  #   branches:
  #     - develop
  push:
    branches: ["mypy_action"]

  # runs on version 20.04 of ubuntu
jobs:
  mypy_type_test:
    runs-on: ubuntu-20.04
    name: Mypy
    steps:

# 1) Checkout the code
      - uses: actions/checkout@v3
# 2) Set up Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

# 3) Install Mypy
      - name: Install Mypy
        run: pip install mypy
# 4) Run Mypy
      - name: Run Mypy
        run: |
          mypy --python-version 3.8 .
