name: Run pytest on pull request to develop

# runs on every pull request to develop
on:
  pull_request:
    branches:
      - develop

# runs on ubuntu-latest
jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
# 1) Add the deadsnakes ppa
      - name: Add deadsnakes ppa
        run: sudo add-apt-repository ppa:deadsnakes/ppa
        # refresh the package list
      - name: Refresh package list
        run: sudo apt-get update
# 2) Install python 3.6
      - name: Install python 3.6
        run: sudo apt-get install python3.6
# 3) Install conda
      - name: Check conda version
        run: conda --version
# 4) Use Setup Miniconda github action
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          environment-file: environment.yml
          activate-environment: resdev36
# 5) Run pytest and generate coverage report (see environment.yml for dependencies)
      - name: Run pytest
      # Specify shell to run the command in
        shell: bash -l {0}
        run: pwd && ls -a 
        # run: python -m pytest src/main.py
# # 4) Install dependencies
#       - name: Install dependencies
#         run: conda env create -f environment.yml
# # 5) Activate environment
#       - name: Activate environment
#         run: $CONDA/bin/activate resdev36
# # 6) run pytest and generate coverage report
#       - name: Run pytest
#         run: python -m pytest src/main.py --cov=src --cov-report=xml
