name: Run pytest on pull request to develop

# runs on every pull request to develop
on:
  pull_request:
    branches:
      - develop

# runs on version 20.04 of ubuntu
jobs:
  pytest-coverage-comment:
    runs-on: ubuntu-20.04
    steps:
# 1) Checkout the code
      - uses: actions/checkout@v3
# 2) Use Setup Miniconda github action to setup environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          environment-file: environment.yml
          activate-environment: resdev36

# 3) Run pytest to run all tests in the tests folder
      - name: Use coverage to run pytest
      # Specify shell to run the command in
        shell: bash -l {0}
        run: |
          coverage run --branch --source=./src -m pytest -ra ./tests --junitxml=junit_result.xml coverage xml -o python_coverage.xml && coverage report -m --fail-under=10
# 4) Get the coverage report in to the pull request comments
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./python_coverage.xml
          junitxml-path: ./junit_result.xml
