name: Run pytest on pull request to develop

# runs on every pull request to develop
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 90-coverage-in-comments

# runs on version 20.04 of ubuntu
jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
# 1) Use Setup Miniconda github action
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          environment-file: environment.yml
          activate-environment: resdev36
  # 2) install pytest and coverage
      - name: Install pytest and coverage
        shell: bash -l {0}
        run: |
          conda install pytest-cov 
# 2) Run pytest to run all tests in the tests folder
      - name: Run pytest
      # Specify shell to run the command in
        shell: bash -l {0}
        # use pytest to generate a coverage report in xml format
        run: |
          # pytest --cov-report xml:pytest.xml --cov=research-and-development/src/ --cov-exclude=tests/
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
# # 3) Display the coverage report in the terminal
#       - name: Display coverage report in terminal
#         shell: bash -l {0}
#         run: coverage report -m
# 4) Get the coverage report in to the pull request comments
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
      # - name: Pytest coverage comment
      #   uses: MishaKav/pytest-coverage-comment@main
      #   with:
      #     pytest-coverage-path: ./pytest-coverage.txt
      #     # pytest-xml-coverage-path: ./pytest.xml
      #     junitxml-path: ./pytest.xml
      #     title: Pytest coverage report
      #     badge-title: Pytest coverage
      #     create-new-comment: true